// Auto-generated by DeukPack V2
use std::io::{Error, ErrorKind};
use std::convert::TryInto;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum WireType {
    Stop = 0,
    Void = 1,
    Bool = 2,
    Byte = 3,
    Double = 4,
    Int16 = 6,
    Int32 = 8,
    Int64 = 10,
    String = 11,
    Struct = 12,
    Map = 13,
    Set = 14,
    List = 15,
}

impl WireType {
    #[inline(always)]
    pub fn from_u8(val: u8) -> Self {
        match val {
            0 => WireType::Stop,
            1 => WireType::Void,
            2 => WireType::Bool,
            3 => WireType::Byte,
            4 => WireType::Double,
            6 => WireType::Int16,
            8 => WireType::Int32,
            10 => WireType::Int64,
            11 => WireType::String,
            12 => WireType::Struct,
            13 => WireType::Map,
            14 => WireType::Set,
            15 => WireType::List,
            _ => WireType::Stop,
        }
    }
}

pub trait ProtocolWriter {
    fn write_byte(&mut self, value: u8);
    fn write_int16(&mut self, value: i16);
    fn write_int32(&mut self, value: i32);
    fn write_int64(&mut self, value: i64);
    fn write_f32(&mut self, value: f32);
    fn write_f64(&mut self, value: f64);
    fn write_bool(&mut self, value: bool);
    fn write_int8(&mut self, value: i8);
    fn write_string(&mut self, value: &str);
    fn write_binary(&mut self, value: &[u8]);
    fn write_field_begin(&mut self, wire_type: WireType, id: i16);
    fn write_field_stop(&mut self);
    fn write_list_begin(&mut self, elem_type: WireType, count: i32);
    fn write_set_begin(&mut self, elem_type: WireType, count: i32);
    fn write_map_begin(&mut self, key_type: WireType, val_type: WireType, count: i32);
    fn get_buffer(&self) -> &[u8];
}

pub trait ProtocolReader {
    fn read_byte(&mut self) -> Result<u8, Error>;
    fn read_int16(&mut self) -> Result<i16, Error>;
    fn read_int32(&mut self) -> Result<i32, Error>;
    fn read_int64(&mut self) -> Result<i64, Error>;
    fn read_f64(&mut self) -> Result<f64, Error>;
    fn read_f32(&mut self) -> Result<f32, Error>;
    fn read_bool(&mut self) -> Result<bool, Error>;
    fn read_int8(&mut self) -> Result<i8, Error>;
    fn read_string(&mut self) -> Result<String, Error>;
    fn read_binary(&mut self) -> Result<Vec<u8>, Error>;
    fn read_field_begin(&mut self) -> Result<(WireType, i16), Error>;
    fn read_list_begin(&mut self) -> Result<(WireType, i32), Error>;
    fn read_set_begin(&mut self) -> Result<(WireType, i32), Error>;
    fn read_map_begin(&mut self) -> Result<(WireType, WireType, i32), Error>;
    
    fn skip(&mut self, wire_type: WireType) -> Result<(), Error> {
        match wire_type {
            WireType::Bool | WireType::Byte => { self.read_byte()?; },
            WireType::Int16 => { self.read_int16()?; },
            WireType::Int32 => { self.read_int32()?; },
            WireType::Int64 | WireType::Double => { self.read_int64()?; },
            WireType::String => { self.read_binary()?; },
            WireType::Struct => {
                loop {
                    let (wt, _) = self.read_field_begin()?;
                    if wt == WireType::Stop { break; }
                    self.skip(wt)?;
                }
            },
            WireType::List | WireType::Set => {
                let (wt, count) = self.read_list_begin()?;
                for _ in 0..count { self.skip(wt)?; }
            },
            WireType::Map => {
                let (kt, vt, count) = self.read_map_begin()?;
                for _ in 0..count {
                    self.skip(kt)?;
                    self.skip(vt)?;
                }
            },
            _ => {}
        }
        Ok(())
    }
}

// -------------------------------------------------------------
// TBinaryProtocol
// -------------------------------------------------------------
pub struct TBinaryProtocolWriter {
    pub buffer: Vec<u8>,
}

impl TBinaryProtocolWriter {
    pub fn new() -> Self { Self { buffer: Vec::with_capacity(1024) } }
}

impl ProtocolWriter for TBinaryProtocolWriter {
    #[inline(always)] fn write_byte(&mut self, value: u8) { self.buffer.push(value); }
    #[inline(always)] fn write_int16(&mut self, value: i16) { self.buffer.extend_from_slice(&value.to_be_bytes()); }
    #[inline(always)] fn write_int32(&mut self, value: i32) { self.buffer.extend_from_slice(&value.to_be_bytes()); }
    #[inline(always)] fn write_int64(&mut self, value: i64) { self.buffer.extend_from_slice(&value.to_be_bytes()); }
    #[inline(always)] fn write_f32(&mut self, value: f32) { self.write_int32(value.to_bits() as i32); }
    #[inline(always)] fn write_f64(&mut self, value: f64) { self.write_int64(value.to_bits() as i64); }
    #[inline(always)] fn write_bool(&mut self, value: bool) { self.write_byte(if value { 1 } else { 0 }); }
    #[inline(always)] fn write_int8(&mut self, value: i8) { self.write_byte(value as u8); }
    #[inline(always)] fn write_string(&mut self, value: &str) {
        let bytes = value.as_bytes();
        self.write_int32(bytes.len() as i32);
        self.buffer.extend_from_slice(bytes);
    }
    #[inline(always)] fn write_binary(&mut self, value: &[u8]) {
        self.write_int32(value.len() as i32);
        self.buffer.extend_from_slice(value);
    }
    #[inline(always)] fn write_field_begin(&mut self, wire_type: WireType, id: i16) {
        self.write_byte(wire_type as u8);
        self.write_int16(id);
    }
    #[inline(always)] fn write_field_stop(&mut self) { self.write_byte(WireType::Stop as u8); }
    #[inline(always)] fn write_list_begin(&mut self, elem_type: WireType, count: i32) {
        self.write_byte(elem_type as u8);
        self.write_int32(count);
    }
    #[inline(always)] fn write_set_begin(&mut self, elem_type: WireType, count: i32) { self.write_list_begin(elem_type, count); }
    #[inline(always)] fn write_map_begin(&mut self, key_type: WireType, val_type: WireType, count: i32) {
        self.write_byte(key_type as u8);
        self.write_byte(val_type as u8);
        self.write_int32(count);
    }
    #[inline(always)] fn get_buffer(&self) -> &[u8] { &self.buffer }
}

pub struct TBinaryProtocolReader<'a> {
    pub buffer: &'a [u8],
    pub offset: usize,
}

impl<'a> TBinaryProtocolReader<'a> {
    pub fn new(buffer: &'a [u8]) -> Self { Self { buffer, offset: 0 } }
}

impl<'a> ProtocolReader for TBinaryProtocolReader<'a> {
    #[inline(always)] fn read_byte(&mut self) -> Result<u8, Error> {
        if self.offset < self.buffer.len() {
            let res = self.buffer[self.offset];
            self.offset += 1;
            Ok(res)
        } else { Ok(0) }
    }
    #[inline(always)] fn read_int16(&mut self) -> Result<i16, Error> {
        if self.offset + 2 > self.buffer.len() { return Ok(0); }
        let bytes = [self.buffer[self.offset], self.buffer[self.offset + 1]];
        self.offset += 2;
        Ok(i16::from_be_bytes(bytes))
    }
    #[inline(always)] fn read_int32(&mut self) -> Result<i32, Error> {
        if self.offset + 4 > self.buffer.len() { return Ok(0); }
        let bytes = [self.buffer[self.offset], self.buffer[self.offset+1], self.buffer[self.offset+2], self.buffer[self.offset+3]];
        self.offset += 4;
        Ok(i32::from_be_bytes(bytes))
    }
    #[inline(always)] fn read_int64(&mut self) -> Result<i64, Error> {
        if self.offset + 8 > self.buffer.len() { return Ok(0); }
        let bytes: [u8; 8] = self.buffer[self.offset..self.offset + 8].try_into().unwrap_or_default();
        self.offset += 8;
        Ok(i64::from_be_bytes(bytes))
    }
    #[inline(always)] fn read_f64(&mut self) -> Result<f64, Error> {
        let val = self.read_int64()?;
        Ok(f64::from_bits(val as u64))
    }
    #[inline(always)] fn read_f32(&mut self) -> Result<f32, Error> {
        let val = self.read_int32()?;
        Ok(f32::from_bits(val as u32))
    }
    #[inline(always)] fn read_bool(&mut self) -> Result<bool, Error> { Ok(self.read_byte()? != 0) }
    #[inline(always)] fn read_int8(&mut self) -> Result<i8, Error> { Ok(self.read_byte()? as i8) }
    #[inline(always)] fn read_string(&mut self) -> Result<String, Error> {
        let len = self.read_int32()? as usize;
        if len == 0 || self.offset + len > self.buffer.len() { return Ok(String::new()); }
        let s = String::from_utf8_lossy(&self.buffer[self.offset..self.offset + len]).into_owned();
        self.offset += len;
        Ok(s)
    }
    #[inline(always)] fn read_binary(&mut self) -> Result<Vec<u8>, Error> {
        let len = self.read_int32()? as usize;
        if len == 0 || self.offset + len > self.buffer.len() { return Ok(Vec::new()); }
        let b = self.buffer[self.offset..self.offset + len].to_vec();
        self.offset += len;
        Ok(b)
    }
    #[inline(always)] fn read_field_begin(&mut self) -> Result<(WireType, i16), Error> {
        let t = self.read_byte()?;
        if t == WireType::Stop as u8 { return Ok((WireType::Stop, 0)); }
        let id = self.read_int16()?;
        Ok((WireType::from_u8(t), id))
    }
    #[inline(always)] fn read_list_begin(&mut self) -> Result<(WireType, i32), Error> {
        let t = self.read_byte()?;
        let c = self.read_int32()?;
        Ok((WireType::from_u8(t), c))
    }
    #[inline(always)] fn read_set_begin(&mut self) -> Result<(WireType, i32), Error> { self.read_list_begin() }
    #[inline(always)] fn read_map_begin(&mut self) -> Result<(WireType, WireType, i32), Error> {
        let k = self.read_byte()?;
        let v = self.read_byte()?;
        let c = self.read_int32()?;
        Ok((WireType::from_u8(k), WireType::from_u8(v), c))
    }
}

// -------------------------------------------------------------
// TCompactProtocol
// -------------------------------------------------------------
pub struct TCompactProtocolWriter {
    pub buffer: Vec<u8>,
}

impl TCompactProtocolWriter {
    pub fn new() -> Self { Self { buffer: Vec::with_capacity(1024) } }
    
    #[inline(always)]
    fn write_varint(&mut self, mut value: u64) {
        while value > 0x7F {
            self.buffer.push(((value & 0x7F) | 0x80) as u8);
            value >>= 7;
        }
        self.buffer.push((value & 0x7F) as u8);
    }
}

impl ProtocolWriter for TCompactProtocolWriter {
    #[inline(always)] fn write_byte(&mut self, value: u8) { self.buffer.push(value); }
    #[inline(always)] fn write_int16(&mut self, value: i16) { self.write_varint(value as u16 as u64); }
    #[inline(always)] fn write_int32(&mut self, value: i32) { self.write_varint(value as u32 as u64); }
    #[inline(always)] fn write_int64(&mut self, value: i64) { self.write_varint(value as u64); }
    #[inline(always)] fn write_f32(&mut self, value: f32) { self.buffer.extend_from_slice(&value.to_le_bytes()); }
    #[inline(always)] fn write_f64(&mut self, value: f64) { self.buffer.extend_from_slice(&value.to_le_bytes()); }
    #[inline(always)] fn write_bool(&mut self, value: bool) { self.write_byte(if value { 1 } else { 0 }); }
    #[inline(always)] fn write_int8(&mut self, value: i8) { self.buffer.push(value as u8); }
    #[inline(always)] fn write_string(&mut self, value: &str) {
        let bytes = value.as_bytes();
        self.write_varint(bytes.len() as u64);
        self.buffer.extend_from_slice(bytes);
    }
    #[inline(always)] fn write_binary(&mut self, value: &[u8]) {
        self.write_varint(value.len() as u64);
        self.buffer.extend_from_slice(value);
    }
    #[inline(always)] fn write_field_begin(&mut self, wire_type: WireType, id: i16) {
        self.write_byte(((id << 4) as u8) | (wire_type as u8));
    }
    #[inline(always)] fn write_field_stop(&mut self) { self.write_byte(WireType::Stop as u8); }
    #[inline(always)] fn write_list_begin(&mut self, elem_type: WireType, count: i32) {
        if count < 15 {
            self.write_byte(((elem_type as u8) << 4) | (count as u8));
        } else {
            self.write_byte(((elem_type as u8) << 4) | 0x0F);
            self.write_varint((count - 15) as u64);
        }
    }
    #[inline(always)] fn write_set_begin(&mut self, elem_type: WireType, count: i32) { self.write_list_begin(elem_type, count); }
    #[inline(always)] fn write_map_begin(&mut self, key_type: WireType, val_type: WireType, count: i32) {
        self.write_varint(count as u64);
        if count > 0 {
            self.write_byte(((key_type as u8) << 4) | (val_type as u8));
        }
    }
    #[inline(always)] fn get_buffer(&self) -> &[u8] { &self.buffer }
}

pub struct TCompactProtocolReader<'a> {
    pub buffer: &'a [u8],
    pub offset: usize,
}

impl<'a> TCompactProtocolReader<'a> {
    pub fn new(buffer: &'a [u8]) -> Self { Self { buffer, offset: 0 } }
    
    #[inline(always)]
    fn read_varint(&mut self) -> Result<u64, Error> {
        let mut result: u64 = 0;
        let mut shift = 0;
        loop {
            if self.offset >= self.buffer.len() { return Ok(0); }
            let b = self.buffer[self.offset];
            self.offset += 1;
            result |= ((b & 0x7F) as u64) << shift;
            shift += 7;
            if (b & 0x80) == 0 { break; }
        }
        Ok(result)
    }
}

impl<'a> ProtocolReader for TCompactProtocolReader<'a> {
    #[inline(always)] fn read_byte(&mut self) -> Result<u8, Error> {
        if self.offset < self.buffer.len() {
            let res = self.buffer[self.offset];
            self.offset += 1;
            Ok(res)
        } else { Ok(0) }
    }
    #[inline(always)] fn read_int16(&mut self) -> Result<i16, Error> { Ok(self.read_varint()? as i16) }
    #[inline(always)] fn read_int32(&mut self) -> Result<i32, Error> { Ok(self.read_varint()? as i32) }
    #[inline(always)] fn read_int64(&mut self) -> Result<i64, Error> { Ok(self.read_varint()? as i64) }
    #[inline(always)] fn read_f64(&mut self) -> Result<f64, Error> {
        if self.offset + 8 > self.buffer.len() { return Ok(0.0); }
        let bytes: [u8; 8] = self.buffer[self.offset..self.offset + 8].try_into().unwrap_or_default();
        self.offset += 8;
        Ok(f64::from_le_bytes(bytes))
    }
    #[inline(always)] fn read_f32(&mut self) -> Result<f32, Error> {
        if self.offset + 4 > self.buffer.len() { return Ok(0.0); }
        let bytes: [u8; 4] = self.buffer[self.offset..self.offset + 4].try_into().unwrap_or_default();
        self.offset += 4;
        Ok(f32::from_le_bytes(bytes))
    }
    #[inline(always)] fn read_bool(&mut self) -> Result<bool, Error> { Ok(self.read_byte()? != 0) }
    #[inline(always)] fn read_int8(&mut self) -> Result<i8, Error> { Ok(self.read_byte()? as i8) }
    #[inline(always)] fn read_string(&mut self) -> Result<String, Error> {
        let len = self.read_varint()? as usize;
        if len == 0 || self.offset + len > self.buffer.len() { return Ok(String::new()); }
        let s = String::from_utf8_lossy(&self.buffer[self.offset..self.offset + len]).into_owned();
        self.offset += len;
        Ok(s)
    }
    #[inline(always)] fn read_binary(&mut self) -> Result<Vec<u8>, Error> {
        let len = self.read_varint()? as usize;
        if len == 0 || self.offset + len > self.buffer.len() { return Ok(Vec::new()); }
        let b = self.buffer[self.offset..self.offset + len].to_vec();
        self.offset += len;
        Ok(b)
    }
    #[inline(always)] fn read_field_begin(&mut self) -> Result<(WireType, i16), Error> {
        let b = self.read_byte()?;
        if b == WireType::Stop as u8 { return Ok((WireType::Stop, 0)); }
        let wt = WireType::from_u8(b & 0x0F);
        let id = (b >> 4) as i16;
        Ok((wt, id))
    }
    #[inline(always)] fn read_list_begin(&mut self) -> Result<(WireType, i32), Error> {
        let b = self.read_byte()?;
        let wt = WireType::from_u8(b & 0x0F);
        let mut count = (b >> 4) as i32;
        if count == 15 { count = self.read_varint()? as i32 + 15; }
        Ok((wt, count))
    }
    #[inline(always)] fn read_set_begin(&mut self) -> Result<(WireType, i32), Error> { self.read_list_begin() }
    #[inline(always)] fn read_map_begin(&mut self) -> Result<(WireType, WireType, i32), Error> {
        let count = self.read_varint()? as i32;
        if count == 0 { return Ok((WireType::Stop, WireType::Stop, 0)); }
        let b = self.read_byte()?;
        Ok((WireType::from_u8(b >> 4), WireType::from_u8(b & 0x0F), count))
    }
}

// -------------------------------------------------------------
// PackProtocol (TCompact + Magic Header)
// -------------------------------------------------------------
pub struct PackProtocolWriter {
    pub inner: TCompactProtocolWriter,
    pub magic_written: bool,
}

impl PackProtocolWriter {
    pub fn new() -> Self { Self { inner: TCompactProtocolWriter::new(), magic_written: false } }
    fn ensure_magic(&mut self) {
        if !self.magic_written {
            self.inner.buffer.extend_from_slice(&[0x44, 0x50, 0x01]);
            self.magic_written = true;
        }
    }
}

impl ProtocolWriter for PackProtocolWriter {
    #[inline(always)] fn write_byte(&mut self, value: u8) { self.inner.write_byte(value); }
    #[inline(always)] fn write_int16(&mut self, value: i16) { self.inner.write_int16(value); }
    #[inline(always)] fn write_int32(&mut self, value: i32) { self.inner.write_int32(value); }
    #[inline(always)] fn write_int64(&mut self, value: i64) { self.inner.write_int64(value); }
    #[inline(always)] fn write_f32(&mut self, value: f32) { self.inner.write_f32(value); }
    #[inline(always)] fn write_f64(&mut self, value: f64) { self.inner.write_f64(value); }
    #[inline(always)] fn write_bool(&mut self, value: bool) { self.inner.write_bool(value); }
    #[inline(always)] fn write_int8(&mut self, value: i8) { self.inner.write_int8(value); }
    #[inline(always)] fn write_string(&mut self, value: &str) { self.inner.write_string(value); }
    #[inline(always)] fn write_binary(&mut self, value: &[u8]) { self.inner.write_binary(value); }
    #[inline(always)] fn write_field_begin(&mut self, wire_type: WireType, id: i16) {
        self.ensure_magic();
        self.inner.write_field_begin(wire_type, id);
    }
    #[inline(always)] fn write_field_stop(&mut self) {
        self.ensure_magic();
        self.inner.write_field_stop();
    }
    #[inline(always)] fn write_list_begin(&mut self, elem_type: WireType, count: i32) { self.inner.write_list_begin(elem_type, count); }
    #[inline(always)] fn write_set_begin(&mut self, elem_type: WireType, count: i32) { self.inner.write_set_begin(elem_type, count); }
    #[inline(always)] fn write_map_begin(&mut self, key_type: WireType, val_type: WireType, count: i32) { self.inner.write_map_begin(key_type, val_type, count); }
    #[inline(always)] fn get_buffer(&self) -> &[u8] { &self.inner.buffer }
}

pub struct PackProtocolReader<'a> {
    pub inner: TCompactProtocolReader<'a>,
    pub magic_skipped: bool,
}

impl<'a> PackProtocolReader<'a> {
    pub fn new(buffer: &'a [u8]) -> Self { Self { inner: TCompactProtocolReader::new(buffer), magic_skipped: false } }
    fn ensure_magic(&mut self) {
        if !self.magic_skipped {
            if self.inner.buffer.len() >= 3 && &self.inner.buffer[0..3] == &[0x44, 0x50, 0x01] {
                self.inner.offset += 3;
            }
            self.magic_skipped = true;
        }
    }
}

impl<'a> ProtocolReader for PackProtocolReader<'a> {
    #[inline(always)] fn read_byte(&mut self) -> Result<u8, Error> { self.inner.read_byte() }
    #[inline(always)] fn read_int16(&mut self) -> Result<i16, Error> { self.inner.read_int16() }
    #[inline(always)] fn read_int32(&mut self) -> Result<i32, Error> { self.inner.read_int32() }
    #[inline(always)] fn read_int64(&mut self) -> Result<i64, Error> { self.inner.read_int64() }
    #[inline(always)] fn read_f64(&mut self) -> Result<f64, Error> { self.inner.read_f64() }
    #[inline(always)] fn read_f32(&mut self) -> Result<f32, Error> { self.inner.read_f32() }
    #[inline(always)] fn read_bool(&mut self) -> Result<bool, Error> { self.inner.read_bool() }
    #[inline(always)] fn read_int8(&mut self) -> Result<i8, Error> { self.inner.read_int8() }
    #[inline(always)] fn read_string(&mut self) -> Result<String, Error> { self.inner.read_string() }
    #[inline(always)] fn read_binary(&mut self) -> Result<Vec<u8>, Error> { self.inner.read_binary() }
    #[inline(always)] fn read_field_begin(&mut self) -> Result<(WireType, i16), Error> {
        self.ensure_magic();
        self.inner.read_field_begin()
    }
    #[inline(always)] fn read_list_begin(&mut self) -> Result<(WireType, i32), Error> { self.inner.read_list_begin() }
    #[inline(always)] fn read_set_begin(&mut self) -> Result<(WireType, i32), Error> { self.inner.read_set_begin() }
    #[inline(always)] fn read_map_begin(&mut self) -> Result<(WireType, WireType, i32), Error> { self.inner.read_map_begin() }
}
