// Generated by DeukPack v@@DEUKPACK_VERSION@@
// @@ISO_TIMESTAMP@@
// JS build pipeline: Path B (direct JS). See DeukPack docs/DEUKPACK_JS_BUILD_PIPELINE.md
// DeukPack JS objects with embedded schema (getSchema(), toJson/fromJson). Consumer-agnostic.
// Protocol helpers: toJson/fromJson (DeukPack JSON), toBinary/fromBinary (binary).
// DeukPack JSON wire uses fixed wrapper keys (i32, str, lst, …) for consumer compatibility; see docs/DEUKPACK_JS_BUILD_PIPELINE.md §2.

