import { DeukPackAST, DeukPackStruct, DeukPackType } from '../../types/DeukPackTypes';
import { RustTypeHelper } from './RustTypeHelper';

export class RustStructGenerator {
  public generate(struct: DeukPackStruct, _ast: DeukPackAST): string {
    const fields = struct.fields.map(f => {
      const type = RustTypeHelper.toRustType(f.type);
      const snakeName = RustTypeHelper.toSnakeCase(f.name);
      return `    pub ${snakeName}: ${type},`;
    }).join('\n');

    const packBody = this.generatePackBody(struct);
    const unpackBody = this.generateUnpackBody(struct);

    return `// Auto-generated by DeukPack V2 (Multi-Protocol)
use crate::dp_protocol::{WireType, ProtocolWriter, ProtocolReader};
use std::io::Error;

#[derive(Debug, Clone, Default)]
pub struct ${struct.name} {
${fields}
}

impl ${struct.name} {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn pack<W: ProtocolWriter>(&self, prot: &mut W) {
${packBody}
        prot.write_field_stop();
    }

    pub fn unpack<R: ProtocolReader>(prot: &mut R) -> Result<Self, Error> {
        let mut obj = Self::new();
${unpackBody}
        Ok(obj)
    }
}
`;
  }

  private generatePackBody(struct: DeukPackStruct): string {
    return struct.fields.map(f => {
      const snakeName = RustTypeHelper.toSnakeCase(f.name);
      const wireType = this.toWireType(f.type);
      return `        prot.write_field_begin(WireType::${wireType}, ${f.id});
        ${this.generateWriteCall(f.type, `self.${snakeName}`)}`;
    }).join('\n');
  }

  private generateWriteCall(type: DeukPackType, varName: string): string {
    if (typeof type === 'string') {
      switch (type) {
        case 'bool': return `prot.write_bool(${varName});`;
        case 'byte': case 'int8': return `prot.write_int8(${varName});`;
        case 'int16': return `prot.write_int16(${varName});`;
        case 'int32': return `prot.write_int32(${varName});`;
        case 'int64': return `prot.write_int64(${varName});`;
        case 'float': return `prot.write_f32(${varName});`;
        case 'double': return `prot.write_f64(${varName});`;
        case 'string': return `prot.write_string(&${varName});`;
        case 'binary': return `prot.write_binary(&${varName});`;
        default: return `${varName}.pack(prot);`; // Struct/Enum
      }
    }

    if (type.type === 'list' || type.type === 'array') {
      const et = this.toWireType(type.elementType);
      return `prot.write_list_begin(WireType::${et}, ${varName}.len() as i32);
        for item in &${varName} {
            ${this.generateWriteCall(type.elementType, '(*item)')}
        }`;
    }
    // TODO: Map, Set
    return `// Map/Set not yet implemented in Rust`;
  }

  private generateUnpackBody(struct: DeukPackStruct): string {
    return `        loop {
            let (wire_type, field_id) = prot.read_field_begin()?;
            if wire_type == WireType::Stop { break; }
            match field_id {
${struct.fields.map(f => `                ${f.id} => {
                    obj.${RustTypeHelper.toSnakeCase(f.name)} = ${this.generateReadCall(f.type)};
                }`).join('\n')}
                _ => prot.skip(wire_type)?,
            }
        }`;
  }

  private generateReadCall(type: DeukPackType): string {
    if (typeof type === 'string') {
      switch (type) {
        case 'bool': return `prot.read_bool()?`;
        case 'byte': case 'int8': return `prot.read_int8()?`;
        case 'int16': return `prot.read_int16()?`;
        case 'int32': return `prot.read_int32()?`;
        case 'int64': return `prot.read_int64()?`;
        case 'float': return `prot.read_f32()?`;
        case 'double': return `prot.read_f64()?`;
        case 'string': return `prot.read_string()?`;
        case 'binary': return `prot.read_binary()?`;
        default: return `${type}::unpack(prot)?`;
      }
    }

    if (type.type === 'list' || type.type === 'array') {
      return `{
                    let (_, count) = prot.read_list_begin()?;
                    let mut vec = Vec::with_capacity(count as usize);
                    for _ in 0..count {
                        vec.push(${this.generateReadCall(type.elementType)});
                    }
                    vec
                }`;
    }
    return `// Map/Set Read TODO`;
  }

  private toWireType(type: DeukPackType): string {
    const t = typeof type === 'string' ? type : type.type;
    switch (t) {
      case 'bool': return 'Bool';
      case 'byte': case 'int8': return 'Byte';
      case 'int16': return 'Int16';
      case 'int32': return 'Int32';
      case 'int64': return 'Int64';
      case 'float': return 'Double';
      case 'double': return 'Double';
      case 'string': return 'String';
      case 'binary': return 'Binary';
      case 'list': case 'array': return 'List';
      case 'set': return 'Set';
      case 'map': return 'Map';
      default: return 'Struct';
    }
  }
}

