// Generated by DeukPack v1.0.0
// 2026-03-20T12:32:23.986Z
// JS build pipeline: Path B (direct JS). See DeukPack docs/DEUKPACK_JS_BUILD_PIPELINE.md
// DeukPack JS objects with embedded schema (getSchema(), toJson/fromJson).
// Protocol helpers: toJson/fromJson (DeukPack JSON), toBinary/fromBinary (binary).

// --- Protocol runtime (DeukPack JSON shape: field-id keys, { i32|str|lst|map|rec|... } wrappers) ---
function _wrapDpJson(type, typeName, val, schemas) {
  if (val === null || val === undefined) return null;
  switch (type) {
    case "Bool": return { tf: !!val };
    case "Byte": case "I16": case "I32": return { i32: Number(val) };
    case "I64": return { i64: Number(val) };
    case "Double": return { dbl: Number(val) };
    case "String": return { str: String(val) };
    case "Binary":
      if (typeof Buffer !== "undefined") return { str: Buffer.from(val).toString("base64") };
      var arr = val && val.length != null ? val : []; var s = ""; for (var i = 0; i < arr.length; i++) s += String.fromCharCode(arr[i] & 255); return { str: (typeof btoa !== "undefined" ? btoa(s) : "") };
    case "List": case "Set":
      var elem = (typeName.match(/^(?:list|set)<(.+)>$/) || [])[1];
      return { lst: (val || []).map(function(e) { return _wrapDpJson(_elemType(elem), elem, e, schemas); }) };
    case "Map":
      var m = (typeName.match(/^map<([^,]+),(.+)>$/) || []);
      var out = {};
      for (var k in val) if (Object.prototype.hasOwnProperty.call(val, k)) out[String(k)] = _wrapDpJson(_elemType(m[2]), m[2], val[k], schemas);
      return { map: out };
    default:
      var s = schemas && schemas[typeName];
      return s ? { rec: _toDpJson(s, val, schemas) } : { str: String(val) };
  }
}
function _elemType(tn) { if (!tn) return "String"; var m = tn.match(/^(?:list|set)<(.+)>$/); return m ? _elemType(m[1]) : (tn === "i32" || tn === "i64" ? "I32" : (tn === "double" ? "Double" : (tn === "string" ? "String" : "Struct"))); }
function _toDpJson(schema, obj, schemas) {
  if (!schema || schema.type !== "Struct" || !schema.fields) return obj;
  var out = {};
  for (var id in schema.fields) { var f = schema.fields[id]; var v = obj && obj[f.name]; if (v === undefined && f.defaultValue !== undefined && f.defaultValue !== null) v = f.defaultValue; if (v !== undefined) out[String(id)] = _wrapDpJson(f.type, f.typeName, v, schemas); }
  return out;
}
function _unwrapDpJson(type, typeName, jsonVal, schemas) {
  if (jsonVal === null || jsonVal === undefined) return null;
  if (type !== "Struct" && typeof jsonVal === "object" && !Array.isArray(jsonVal)) {
    if (type === "Binary" && jsonVal.str) { var b64 = jsonVal.str; if (typeof Buffer !== "undefined") return new Uint8Array(Buffer.from(b64, "base64")); var bin = typeof atob !== "undefined" ? atob(b64) : ""; var arr = new Uint8Array(bin.length); for (var i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i); return arr; }
    if (jsonVal.str !== undefined) return jsonVal.str;
    if (jsonVal.i32 !== undefined) return jsonVal.i32;
    if (jsonVal.i64 !== undefined) return Number(jsonVal.i64);
    if (jsonVal.dbl !== undefined) return jsonVal.dbl;
    if (jsonVal.tf !== undefined) return jsonVal.tf;
    if (jsonVal.lst !== undefined) { var elem = (typeName.match(/^(?:list|set)<(.+)>$/) || [])[1]; return jsonVal.lst.map(function(e) { return _unwrapDpJson(_elemType(elem), elem, e, schemas); }); }
    if (jsonVal.map !== undefined) { var m = (typeName.match(/^map<([^,]+),(.+)>$/) || []); var o = {}; for (var k in jsonVal.map) o[k] = _unwrapDpJson(_elemType(m[2]), m[2], jsonVal.map[k], schemas); return o; }
    if (jsonVal.rec !== undefined) { var s = schemas && schemas[typeName]; return s ? _fromDpJson(s, jsonVal.rec, schemas) : jsonVal.rec; }
  }
  return jsonVal;
}
function _fromDpJson(schema, jsonObj, schemas) {
  if (!schema || schema.type !== "Struct" || !schema.fields) return jsonObj || {};
  var out = {};
  for (var id in schema.fields) { var f = schema.fields[id]; var w = jsonObj && jsonObj[String(id)]; if (w !== undefined) out[f.name] = _unwrapDpJson(f.type, f.typeName, w, schemas); }
  return out;
}

// Excel row constants: Row 1=HIERARCHY_ID, Row 2=DATATYPE, Row 5+=DATA
var _XL_HIER_ROW = 1, _XL_DT_ROW = 2, _XL_FIRST_DATA = 5;
function _xlBuildColMap(sheet) {
  var m = {}; for (var c = 1; c <= sheet.lastColumn; c++) { var h = (sheet.cellValue(_XL_HIER_ROW, c) || "").trim(); if (!h) break; m[h] = { col: c, dt: (sheet.cellValue(_XL_DT_ROW, c) || "").trim() }; } return m;
}
function _xlParsePrimitive(type, raw, dt, enums) {
  if (raw === null || raw === undefined || raw === "") return type === "String" ? "" : undefined;
  var tok = String(raw).split(":")[0].trim();
  switch (type) {
    case "Bool": return tok === "1" || tok.toLowerCase() === "true";
    case "Byte": case "I16": case "I32":
      var n = parseInt(tok, 10); if (!isNaN(n)) return n;
      if (enums && dt && dt.indexOf("enum") === 0) { var en = dt.replace(/^enum[<(]|[>)]$/g,""); var ed = enums[en]; if (ed && ed.values && ed.values[tok] !== undefined) return ed.values[tok]; }
      return 0;
    case "I64": return parseInt(tok, 10) || 0;
    case "Double": return parseFloat(raw) || 0;
    case "String": return String(raw).trim();
    default: return String(raw).trim();
  }
}
function _xlMapType(tn) { var m = {i32:"I32",i64:"I64",i16:"I16",i8:"Byte",byte:"Byte",double:"Double",dbl:"Double",string:"String",str:"String",bool:"Bool",tf:"Bool"}; return m[tn] || "Struct"; }
function _xlCountListRows(sheet, row, listPath, colMap) {
  var tuid = sheet.cellValue(row, 1) || "", pfx = listPath + ".", cnt = 0;
  for (var r = row; r <= sheet.lastRow; r++) {
    if (r > row) { var rid = sheet.cellValue(r, 1) || ""; if (rid && rid !== tuid) break; }
    var has = false; for (var p in colMap) { if ((p === listPath || p.indexOf(pfx) === 0) && !sheet.isCellEmpty(r, colMap[p].col)) { has = true; break; } }
    if (has) cnt++; else if (cnt > 0) break;
  } return cnt;
}
function _xlReadField(field, fid, colMap, sheet, row, schemas, enums, parentPath) {
  var fp = parentPath ? parentPath + "." + fid : String(fid);
  var type = field.type, tn = field.typeName;
  if (type === "Struct") {
    var cs = schemas[tn]; if (!cs || !cs.fields) return undefined;
    var obj = {}, has = false;
    for (var cid in cs.fields) { var cf = cs.fields[cid]; var v = _xlReadField(cf, cid, colMap, sheet, row, schemas, enums, fp); if (v !== undefined && v !== null) { obj[cf.name] = v; has = true; } }
    return has ? obj : undefined;
  }
  if (type === "List" || type === "Set") {
    var cnt = _xlCountListRows(sheet, row, fp, colMap); if (cnt === 0) return undefined;
    var em = (tn.match(/^(?:list|set)<(.+)>$/) || [])[1] || "struct";
    var isPrim = ["i32","i64","i16","i8","double","string","bool","byte","dbl","str","tf"].indexOf(em) >= 0;
    var arr = [], pfx = fp + ".";
    for (var i = 0; i < cnt; i++) { var er = row + i;
      if (isPrim) { for (var p in colMap) { if (p.indexOf(pfx) === 0) { arr.push(_xlParsePrimitive(_xlMapType(em), sheet.cellValue(er, colMap[p].col), colMap[p].dt, enums)); break; } } }
      else { var es = schemas[em], eo = {};
        if (es && es.fields) { for (var cid in es.fields) { var cf = es.fields[cid]; var v = _xlReadField(cf, cid, colMap, sheet, er, schemas, enums, fp); if (v !== undefined && v !== null) eo[cf.name] = v; } }
        else { for (var p in colMap) { if (p.indexOf(pfx) === 0) { var rem = p.substring(pfx.length); if (rem.indexOf(".") < 0 && !sheet.isCellEmpty(er, colMap[p].col)) eo[rem] = sheet.cellValue(er, colMap[p].col); } } }
        arr.push(eo);
      }
    } return arr.length > 0 ? arr : undefined;
  }
  var e = colMap[fp]; if (!e) return undefined;
  if (sheet.isCellEmpty(row, e.col)) return undefined;
  return _xlParsePrimitive(type, sheet.cellValue(row, e.col), e.dt, enums);
}
function _fromExcelRow(schema, sheet, row, schemas, enums) {
  if (!schema || schema.type !== "Struct" || !schema.fields) return {};
  var colMap = _xlBuildColMap(sheet), out = {};
  for (var fid in schema.fields) { var f = schema.fields[fid]; var v = _xlReadField(f, fid, colMap, sheet, row, schemas, enums); if (v !== undefined && v !== null) out[f.name] = v; }
  return out;
}
function _fromExcelSheet(schema, sheet, schemas, enums, firstRow) {
  firstRow = firstRow || _XL_FIRST_DATA; var result = {};
  for (var r = firstRow; r <= sheet.lastRow; r++) { var tuid = sheet.cellValue(r, 1); if (!tuid) continue; var id = parseInt(String(tuid).split(":")[0], 10); if (isNaN(id)) continue; result[id] = _fromExcelRow(schema, sheet, r, schemas, enums); }
  return result;
}

// --- WriteWithOverrides runtime: apply field-id overrides without cloning ---
function _applyOverrides(obj, overrides, schema) {
  if (!overrides || !schema || !schema.fields) return obj;
  var out = {};
  for (var k in obj) if (Object.prototype.hasOwnProperty.call(obj, k)) out[k] = obj[k];
  for (var id in overrides) {
    var f = schema.fields[id];
    if (f) out[f.name] = overrides[id];
  }
  return out;
}

// --- WriteFields runtime: project only specified field IDs (+ optional overrides) ---
function _projectFields(obj, fieldIds, schema, overrides) {
  if (!fieldIds || !schema || !schema.fields) return {};
  var set = {}; for (var i = 0; i < fieldIds.length; i++) set[fieldIds[i]] = true;
  var out = {};
  for (var fid in schema.fields) {
    if (!set[fid]) continue;
    var f = schema.fields[fid];
    out[f.name] = (overrides && overrides[fid] !== undefined) ? overrides[fid] : obj[f.name];
  }
  return out;
}

const _schema_DemoPoint = {"name":"DemoPoint","type":"Struct","fields":{"1":{"id":1,"name":"x","type":"Struct","typeName":"int32","required":false,"defaultValue":null},"2":{"id":2,"name":"y","type":"Struct","typeName":"int32","required":false,"defaultValue":null}}};
const DemoPoint = {
  getSchema() { return _schema_DemoPoint; },
  create() { return {}; },
  toJson(obj) { return JSON.stringify(_toDpJson(_schema_DemoPoint, obj, _schemas)); },
  fromJson(str) { return _fromDpJson(_schema_DemoPoint, JSON.parse(str || "{}"), _schemas); },
  toBinary(obj) { throw new Error("toBinary: use C#/TS runtime or DeukPack binary protocol"); },
  fromBinary(buf) { throw new Error("fromBinary: use C#/TS runtime or DeukPack binary protocol"); },
  fromExcel(sheet, row) { return _fromExcelRow(_schema_DemoPoint, sheet, row, _schemas, _enums); },
  fromExcelSheet(sheet, firstRow) { return _fromExcelSheet(_schema_DemoPoint, sheet, _schemas, _enums, firstRow); },
  applyOverrides(obj, overrides) { return _applyOverrides(obj, overrides, _schema_DemoPoint); },
  toJsonWithOverrides(obj, overrides) { return JSON.stringify(_toDpJson(_schema_DemoPoint, _applyOverrides(obj, overrides, _schema_DemoPoint), _schemas)); },
  projectFields(obj, fieldIds, overrides) { return _projectFields(obj, fieldIds, _schema_DemoPoint, overrides); },
  toJsonWithFields(obj, fieldIds, overrides) { return JSON.stringify(_toDpJson(_schema_DemoPoint, _projectFields(obj, fieldIds, _schema_DemoPoint, overrides), _schemas)); },
  FieldId: { X: 1, Y: 2 }
};

const _schema_DemoUser = {"name":"DemoUser","type":"Struct","fields":{"1":{"id":1,"name":"id","type":"Struct","typeName":"int32","required":false,"defaultValue":null},"2":{"id":2,"name":"name","type":"String","typeName":"string","required":false,"defaultValue":null},"3":{"id":3,"name":"home","type":"Struct","typeName":"DemoPoint","required":false,"defaultValue":null}}};
const DemoUser = {
  getSchema() { return _schema_DemoUser; },
  create() { return {}; },
  toJson(obj) { return JSON.stringify(_toDpJson(_schema_DemoUser, obj, _schemas)); },
  fromJson(str) { return _fromDpJson(_schema_DemoUser, JSON.parse(str || "{}"), _schemas); },
  toBinary(obj) { throw new Error("toBinary: use C#/TS runtime or DeukPack binary protocol"); },
  fromBinary(buf) { throw new Error("fromBinary: use C#/TS runtime or DeukPack binary protocol"); },
  fromExcel(sheet, row) { return _fromExcelRow(_schema_DemoUser, sheet, row, _schemas, _enums); },
  fromExcelSheet(sheet, firstRow) { return _fromExcelSheet(_schema_DemoUser, sheet, _schemas, _enums, firstRow); },
  applyOverrides(obj, overrides) { return _applyOverrides(obj, overrides, _schema_DemoUser); },
  toJsonWithOverrides(obj, overrides) { return JSON.stringify(_toDpJson(_schema_DemoUser, _applyOverrides(obj, overrides, _schema_DemoUser), _schemas)); },
  projectFields(obj, fieldIds, overrides) { return _projectFields(obj, fieldIds, _schema_DemoUser, overrides); },
  toJsonWithFields(obj, fieldIds, overrides) { return JSON.stringify(_toDpJson(_schema_DemoUser, _projectFields(obj, fieldIds, _schema_DemoUser, overrides), _schemas)); },
  FieldId: { Id: 1, Name: 2, Home: 3 }
};

const _schema_UserRecord = {"name":"UserRecord","type":"Struct","fields":{"1":{"id":1,"name":"id","type":"Struct","typeName":"int32","required":false,"defaultValue":null},"2":{"id":2,"name":"displayName","type":"String","typeName":"string","required":false,"defaultValue":null},"3":{"id":3,"name":"level","type":"Struct","typeName":"int32","required":false,"defaultValue":null},"4":{"id":4,"name":"avatarUrl","type":"String","typeName":"string","required":false,"defaultValue":null}},"docComment":"WriteFields sample: project a subset of fields at runtime"};
const UserRecord = {
  getSchema() { return _schema_UserRecord; },
  create() { return {}; },
  toJson(obj) { return JSON.stringify(_toDpJson(_schema_UserRecord, obj, _schemas)); },
  fromJson(str) { return _fromDpJson(_schema_UserRecord, JSON.parse(str || "{}"), _schemas); },
  toBinary(obj) { throw new Error("toBinary: use C#/TS runtime or DeukPack binary protocol"); },
  fromBinary(buf) { throw new Error("fromBinary: use C#/TS runtime or DeukPack binary protocol"); },
  fromExcel(sheet, row) { return _fromExcelRow(_schema_UserRecord, sheet, row, _schemas, _enums); },
  fromExcelSheet(sheet, firstRow) { return _fromExcelSheet(_schema_UserRecord, sheet, _schemas, _enums, firstRow); },
  applyOverrides(obj, overrides) { return _applyOverrides(obj, overrides, _schema_UserRecord); },
  toJsonWithOverrides(obj, overrides) { return JSON.stringify(_toDpJson(_schema_UserRecord, _applyOverrides(obj, overrides, _schema_UserRecord), _schemas)); },
  projectFields(obj, fieldIds, overrides) { return _projectFields(obj, fieldIds, _schema_UserRecord, overrides); },
  toJsonWithFields(obj, fieldIds, overrides) { return JSON.stringify(_toDpJson(_schema_UserRecord, _projectFields(obj, fieldIds, _schema_UserRecord, overrides), _schemas)); },
  FieldId: { Id: 1, DisplayName: 2, Level: 3, AvatarUrl: 4 }
};

const _schema_UserBase = {"name":"UserBase","type":"Struct","fields":{"1":{"id":1,"name":"id","type":"Struct","typeName":"int32","required":false,"defaultValue":null},"2":{"id":2,"name":"tag","type":"String","typeName":"string","required":false,"defaultValue":null}},"docComment":"extends sample: parent fields merged into child at codegen"};
const UserBase = {
  getSchema() { return _schema_UserBase; },
  create() { return {}; },
  toJson(obj) { return JSON.stringify(_toDpJson(_schema_UserBase, obj, _schemas)); },
  fromJson(str) { return _fromDpJson(_schema_UserBase, JSON.parse(str || "{}"), _schemas); },
  toBinary(obj) { throw new Error("toBinary: use C#/TS runtime or DeukPack binary protocol"); },
  fromBinary(buf) { throw new Error("fromBinary: use C#/TS runtime or DeukPack binary protocol"); },
  fromExcel(sheet, row) { return _fromExcelRow(_schema_UserBase, sheet, row, _schemas, _enums); },
  fromExcelSheet(sheet, firstRow) { return _fromExcelSheet(_schema_UserBase, sheet, _schemas, _enums, firstRow); },
  applyOverrides(obj, overrides) { return _applyOverrides(obj, overrides, _schema_UserBase); },
  toJsonWithOverrides(obj, overrides) { return JSON.stringify(_toDpJson(_schema_UserBase, _applyOverrides(obj, overrides, _schema_UserBase), _schemas)); },
  projectFields(obj, fieldIds, overrides) { return _projectFields(obj, fieldIds, _schema_UserBase, overrides); },
  toJsonWithFields(obj, fieldIds, overrides) { return JSON.stringify(_toDpJson(_schema_UserBase, _projectFields(obj, fieldIds, _schema_UserBase, overrides), _schemas)); },
  FieldId: { Id: 1, Tag: 2 }
};

const _schema_UserFull = {"name":"UserFull","type":"Struct","fields":{"1":{"id":1,"name":"id","type":"Struct","typeName":"int32","required":false,"defaultValue":null},"2":{"id":2,"name":"tag","type":"String","typeName":"string","required":false,"defaultValue":null},"3":{"id":3,"name":"level","type":"Struct","typeName":"int32","required":false,"defaultValue":null}}};
const UserFull = {
  getSchema() { return _schema_UserFull; },
  create() { return {}; },
  toJson(obj) { return JSON.stringify(_toDpJson(_schema_UserFull, obj, _schemas)); },
  fromJson(str) { return _fromDpJson(_schema_UserFull, JSON.parse(str || "{}"), _schemas); },
  toBinary(obj) { throw new Error("toBinary: use C#/TS runtime or DeukPack binary protocol"); },
  fromBinary(buf) { throw new Error("fromBinary: use C#/TS runtime or DeukPack binary protocol"); },
  fromExcel(sheet, row) { return _fromExcelRow(_schema_UserFull, sheet, row, _schemas, _enums); },
  fromExcelSheet(sheet, firstRow) { return _fromExcelSheet(_schema_UserFull, sheet, _schemas, _enums, firstRow); },
  applyOverrides(obj, overrides) { return _applyOverrides(obj, overrides, _schema_UserFull); },
  toJsonWithOverrides(obj, overrides) { return JSON.stringify(_toDpJson(_schema_UserFull, _applyOverrides(obj, overrides, _schema_UserFull), _schemas)); },
  projectFields(obj, fieldIds, overrides) { return _projectFields(obj, fieldIds, _schema_UserFull, overrides); },
  toJsonWithFields(obj, fieldIds, overrides) { return JSON.stringify(_toDpJson(_schema_UserFull, _projectFields(obj, fieldIds, _schema_UserFull, overrides), _schemas)); },
  FieldId: { Id: 1, Tag: 2, Level: 3 }
};

var _schemas = {};
_schemas["DemoPoint"] = _schema_DemoPoint;
_schemas["DemoUser"] = _schema_DemoUser;
_schemas["UserRecord"] = _schema_UserRecord;
_schemas["UserBase"] = _schema_UserBase;
_schemas["UserFull"] = _schema_UserFull;
var _enums = {};

if (typeof module !== "undefined" && module.exports) {
  module.exports.DemoPoint = DemoPoint;
  module.exports.DemoUser = DemoUser;
  module.exports.UserRecord = UserRecord;
  module.exports.UserBase = UserBase;
  module.exports.UserFull = UserFull;
}
