// Autogenerated by DeukPack v1.4.0 | https://deukpack.app
// Powered by DeukPack — Universal IDL Gateway for AI & Unity
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//  @generated

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Runtime.Serialization;
using System.Linq;
using DeukPack.Protocol;


namespace deuk.test
{

  using DpProtocol = DeukPack.Protocol.DpProtocol;


// Autogenerated by DeukPack v1.4.0 | https://deukpack.app
// Powered by DeukPack — Universal IDL Gateway for AI & Unity
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//  @generated

  public enum TestEnum
  {
    Alpha = 1,
    Beta = 2,
    Gamma = 3
  }


// Autogenerated by DeukPack v1.4.0 | https://deukpack.app
// Powered by DeukPack — Universal IDL Gateway for AI & Unity
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//  @generated

  [System.Serializable]
  public partial class RoundtripModel : IDeukPack
  {

    public bool B_val { get; set; } = true;
    public sbyte I8_val { get; set; } = 8;
    public short I16_val { get; set; } = 1616;
    public int I32_val { get; set; } = 323232;
    public long I64_val { get; set; } = 6464646464L;
    public float F_val { get; set; } = 3.14f;
    public double D_val { get; set; } = 2.71828;
    public string S_val { get; set; } = "Hello DeukPack World";
    public byte[] Bin_val { get; set; }
    public List<int> I32_list { get; set; }
    public List<string> S_list { get; set; }
    public Dictionary<string, int> S_i32_map { get; set; }
    public deuk.test.NestedStruct Nested { get; set; }

    public static class FieldId
    {
      public const int B_val = 1;
      public const int I8_val = 2;
      public const int I16_val = 3;
      public const int I32_val = 4;
      public const int I64_val = 5;
      public const int F_val = 6;
      public const int D_val = 7;
      public const int S_val = 8;
      public const int Bin_val = 9;
      public const int I32_list = 10;
      public const int S_list = 11;
      public const int S_i32_map = 12;
      public const int Nested = 13;
    }
    // 기본값 정적 노출 (enum/구조체 공통, 리플렉션 없이 조회)
    public static bool Default_B_val => true;
    public static sbyte Default_I8_val => 8;
    public static short Default_I16_val => 1616;
    public static int Default_I32_val => 323232;
    public static long Default_I64_val => 6464646464L;
    public static float Default_F_val => 3.14f;
    public static double Default_D_val => 2.71828;
    public static string Default_S_val => "Hello DeukPack World";

    // Serialization methods
    public void Write(DpProtocol oprot) => Write(oprot, null, null);

    public void Write(DpProtocol oprot, ICollection<int>? fieldIds, Dictionary<int, object>? overrides = null)
    {
      if (fieldIds != null && fieldIds.Count == 0) return;
      DpRecord struc = new DpRecord("RoundtripModel", 13);
      oprot.WriteStructBegin(struc);
      // field 1: b_val
      if (fieldIds == null || fieldIds.Contains(1))
      {
        var _v1 = (overrides != null && overrides.TryGetValue(1, out var _o1)) ? (bool)_o1 : this.B_val;
        if (_v1 != true)
        {
          DpColumn field = new DpColumn("b_val", DpWireType.Bool, 1);
          oprot.WriteFieldBegin(field);
          DeukPackSerializer.WriteValue(oprot, DpWireType.Bool, _v1);
          oprot.WriteFieldEnd();
        }
      }
      // field 2: i8_val
      if (fieldIds == null || fieldIds.Contains(2))
      {
        var _v2 = (overrides != null && overrides.TryGetValue(2, out var _o2)) ? (sbyte)_o2 : this.I8_val;
        if (_v2 != 8)
        {
          DpColumn field = new DpColumn("i8_val", DpWireType.Byte, 2);
          oprot.WriteFieldBegin(field);
          DeukPackSerializer.WriteValue(oprot, DpWireType.Byte, _v2);
          oprot.WriteFieldEnd();
        }
      }
      // field 3: i16_val
      if (fieldIds == null || fieldIds.Contains(3))
      {
        var _v3 = (overrides != null && overrides.TryGetValue(3, out var _o3)) ? (short)_o3 : this.I16_val;
        if (_v3 != 1616)
        {
          DpColumn field = new DpColumn("i16_val", DpWireType.Int16, 3);
          oprot.WriteFieldBegin(field);
          DeukPackSerializer.WriteValue(oprot, DpWireType.Int16, _v3);
          oprot.WriteFieldEnd();
        }
      }
      // field 4: i32_val
      if (fieldIds == null || fieldIds.Contains(4))
      {
        var _v4 = (overrides != null && overrides.TryGetValue(4, out var _o4)) ? (int)_o4 : this.I32_val;
        if (_v4 != 323232)
        {
          DpColumn field = new DpColumn("i32_val", DpWireType.Int32, 4);
          oprot.WriteFieldBegin(field);
          DeukPackSerializer.WriteValue(oprot, DpWireType.Int32, _v4);
          oprot.WriteFieldEnd();
        }
      }
      // field 5: i64_val
      if (fieldIds == null || fieldIds.Contains(5))
      {
        var _v5 = (overrides != null && overrides.TryGetValue(5, out var _o5)) ? (long)_o5 : this.I64_val;
        if (_v5 != 6464646464L)
        {
          DpColumn field = new DpColumn("i64_val", DpWireType.Int64, 5);
          oprot.WriteFieldBegin(field);
          DeukPackSerializer.WriteValue(oprot, DpWireType.Int64, _v5);
          oprot.WriteFieldEnd();
        }
      }
      // field 6: f_val
      if (fieldIds == null || fieldIds.Contains(6))
      {
        var _v6 = (overrides != null && overrides.TryGetValue(6, out var _o6)) ? (float)_o6 : this.F_val;
        if (_v6 != 3.14f)
        {
          DpColumn field = new DpColumn("f_val", DpWireType.Double, 6);
          oprot.WriteFieldBegin(field);
          DeukPackSerializer.WriteValue(oprot, DpWireType.Double, _v6);
          oprot.WriteFieldEnd();
        }
      }
      // field 7: d_val
      if (fieldIds == null || fieldIds.Contains(7))
      {
        var _v7 = (overrides != null && overrides.TryGetValue(7, out var _o7)) ? (double)_o7 : this.D_val;
        if (_v7 != 2.71828)
        {
          DpColumn field = new DpColumn("d_val", DpWireType.Double, 7);
          oprot.WriteFieldBegin(field);
          DeukPackSerializer.WriteValue(oprot, DpWireType.Double, _v7);
          oprot.WriteFieldEnd();
        }
      }
      // field 8: s_val
      if (fieldIds == null || fieldIds.Contains(8))
      {
        var _v8 = (overrides != null && overrides.TryGetValue(8, out var _o8)) ? (string)_o8 : this.S_val;
        if (_v8 != "Hello DeukPack World")
        {
          DpColumn field = new DpColumn("s_val", DpWireType.String, 8);
          oprot.WriteFieldBegin(field);
          DeukPackSerializer.WriteValue(oprot, DpWireType.String, _v8);
          oprot.WriteFieldEnd();
        }
      }
      // field 9: bin_val
      if (fieldIds == null || fieldIds.Contains(9))
      {
        var _v9 = (overrides != null && overrides.TryGetValue(9, out var _o9)) ? (byte[])_o9 : this.Bin_val;
        if (_v9 != null)
        {
          DpColumn field = new DpColumn("bin_val", DpWireType.String, 9);
          oprot.WriteFieldBegin(field);
          DeukPackSerializer.WriteValue(oprot, DpWireType.String, _v9);
          oprot.WriteFieldEnd();
        }
      }
      // field 10: i32_list
      if (fieldIds == null || fieldIds.Contains(10))
      {
        var _v10 = (overrides != null && overrides.TryGetValue(10, out var _o10)) ? (List<int>)_o10 : this.I32_list;
        if (_v10 != null)
        {
          DpColumn field = new DpColumn("i32_list", DpWireType.List, 10);
          oprot.WriteFieldBegin(field);
          DeukPackSerializer.WriteList<int>(oprot, DpWireType.Int32, _v10);
          oprot.WriteFieldEnd();
        }
      }
      // field 11: s_list
      if (fieldIds == null || fieldIds.Contains(11))
      {
        var _v11 = (overrides != null && overrides.TryGetValue(11, out var _o11)) ? (List<string>)_o11 : this.S_list;
        if (_v11 != null)
        {
          DpColumn field = new DpColumn("s_list", DpWireType.List, 11);
          oprot.WriteFieldBegin(field);
          DeukPackSerializer.WriteList<string>(oprot, DpWireType.String, _v11);
          oprot.WriteFieldEnd();
        }
      }
      // field 12: s_i32_map
      if (fieldIds == null || fieldIds.Contains(12))
      {
        var _v12 = (overrides != null && overrides.TryGetValue(12, out var _o12)) ? (Dictionary<string, int>)_o12 : this.S_i32_map;
        if (_v12 != null)
        {
          DpColumn field = new DpColumn("s_i32_map", DpWireType.Map, 12);
          oprot.WriteFieldBegin(field);
          DeukPackSerializer.WriteMap<string, int>(oprot, DpWireType.String, DpWireType.Int32, _v12);
          oprot.WriteFieldEnd();
        }
      }
      // field 13: nested
      if (fieldIds == null || fieldIds.Contains(13))
      {
        var _v13 = (overrides != null && overrides.TryGetValue(13, out var _o13)) ? (deuk.test.NestedStruct)_o13 : this.Nested;
        if (_v13 != null)
        {
          DpColumn field = new DpColumn("nested", DpWireType.Struct, 13);
          oprot.WriteFieldBegin(field);
          DeukPackSerializer.WriteValue(oprot, DpWireType.Struct, _v13);
          oprot.WriteFieldEnd();
        }
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public void Read(DpProtocol iprot)
    {
      this.B_val = true;
      this.I8_val = 8;
      this.I16_val = 1616;
      this.I32_val = 323232;
      this.I64_val = 6464646464L;
      this.F_val = 3.14f;
      this.D_val = 2.71828;
      this.S_val = "Hello DeukPack World";
      this.Bin_val = null;
      this.I32_list = new List<int>();
      this.S_list = new List<string>();
      this.S_i32_map = new Dictionary<string, int>();
      this.Nested = deuk.test.NestedStruct.CreateDefault();
      DpColumn field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == DpWireType.Stop)
        {
          break;
        }
        if (field.ID == 0 && !string.IsNullOrEmpty(field.Name))
        {
          if (field.Name == "b_val") field.ID = 1;
          else           if (field.Name == "i8_val") field.ID = 2;
          else           if (field.Name == "i16_val") field.ID = 3;
          else           if (field.Name == "i32_val") field.ID = 4;
          else           if (field.Name == "i64_val") field.ID = 5;
          else           if (field.Name == "f_val") field.ID = 6;
          else           if (field.Name == "d_val") field.ID = 7;
          else           if (field.Name == "s_val") field.ID = 8;
          else           if (field.Name == "bin_val") field.ID = 9;
          else           if (field.Name == "i32_list") field.ID = 10;
          else           if (field.Name == "s_list") field.ID = 11;
          else           if (field.Name == "s_i32_map") field.ID = 12;
          else           if (field.Name == "nested") field.ID = 13;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == DpWireType.Bool || field.Type == DpWireType.Void)
            {
              this.B_val = (bool)DeukPackSerializer.ReadValue(iprot, DpWireType.Bool, typeof(bool))!;
            }
            else
            {
              DpProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == DpWireType.Byte || field.Type == DpWireType.Void)
            {
              this.I8_val = (sbyte)DeukPackSerializer.ReadValue(iprot, DpWireType.Byte, typeof(sbyte))!;
            }
            else
            {
              DpProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == DpWireType.Int16 || field.Type == DpWireType.Void)
            {
              this.I16_val = (short)DeukPackSerializer.ReadValue(iprot, DpWireType.Int16, typeof(short))!;
            }
            else
            {
              DpProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == DpWireType.Int32 || field.Type == DpWireType.Void)
            {
              this.I32_val = (int)DeukPackSerializer.ReadValue(iprot, DpWireType.Int32, typeof(int))!;
            }
            else
            {
              DpProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == DpWireType.Int64 || field.Type == DpWireType.Void)
            {
              this.I64_val = (long)DeukPackSerializer.ReadValue(iprot, DpWireType.Int64, typeof(long))!;
            }
            else
            {
              DpProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == DpWireType.Double || field.Type == DpWireType.Void)
            {
              this.F_val = (float)DeukPackSerializer.ReadValue(iprot, DpWireType.Double, typeof(float))!;
            }
            else
            {
              DpProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 7:
            if (field.Type == DpWireType.Double || field.Type == DpWireType.Void)
            {
              this.D_val = (double)DeukPackSerializer.ReadValue(iprot, DpWireType.Double, typeof(double))!;
            }
            else
            {
              DpProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 8:
            if (field.Type == DpWireType.String || field.Type == DpWireType.Void)
            {
              this.S_val = (string)DeukPackSerializer.ReadValue(iprot, DpWireType.String, typeof(string))!;
            }
            else
            {
              DpProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 9:
            if (field.Type == DpWireType.String || field.Type == DpWireType.Void)
            {
              this.Bin_val = (byte[])DeukPackSerializer.ReadValue(iprot, DpWireType.String, typeof(byte[]))!;
            }
            else
            {
              DpProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 10:
            if (field.Type == DpWireType.List || field.Type == DpWireType.Void)
            {
              this.I32_list = DeukPackSerializer.ReadList<int>(iprot, DpWireType.Int32);
            }
            else
            {
              DpProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 11:
            if (field.Type == DpWireType.List || field.Type == DpWireType.Void)
            {
              this.S_list = DeukPackSerializer.ReadList<string>(iprot, DpWireType.String);
            }
            else
            {
              DpProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 12:
            if (field.Type == DpWireType.Map || field.Type == DpWireType.Void)
            {
              this.S_i32_map = DeukPackSerializer.ReadMap<string, int>(iprot, DpWireType.String, DpWireType.Int32);
            }
            else
            {
              DpProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 13:
            if (field.Type == DpWireType.Struct || field.Type == DpWireType.Void)
            {
              this.Nested = (deuk.test.NestedStruct)DeukPackSerializer.ReadValue(iprot, DpWireType.Struct, typeof(deuk.test.NestedStruct))! ?? deuk.test.NestedStruct.CreateDefault();
            }
            else
            {
              DpProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default:
            DeukPack.Protocol.DeukPackSerializationWarnings.LogUnknownField("RoundtripModel", field.ID, field.Name ?? "");
            DpProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();

    }

    // Clone method
    public RoundtripModel Clone()
    {
      var clone = new RoundtripModel();
      clone.B_val = this.B_val;
      clone.I8_val = this.I8_val;
      clone.I16_val = this.I16_val;
      clone.I32_val = this.I32_val;
      clone.I64_val = this.I64_val;
      clone.F_val = this.F_val;
      clone.D_val = this.D_val;
      clone.S_val = this.S_val;
      clone.Bin_val = this.Bin_val != null ? ((byte[])this.Bin_val.Clone()) : null!;
      clone.I32_list = this.I32_list != null ? (this.I32_list.Select(item => item).ToList()) : null!;
      clone.S_list = this.S_list != null ? (this.S_list.Select(item => item).ToList()) : null!;
      clone.S_i32_map = this.S_i32_map != null ? (this.S_i32_map.ToDictionary(kvp => kvp.Key, kvp => kvp.Value)) : null!;
      clone.Nested = this.Nested != null ? (this.Nested.Clone()) : null!;
      return clone;
    }

    // Explicit interface implementation
    object IDeukPack.Clone()
    {
      return this.Clone();
    }

    // CreateDefault: recursive default instance
    public static RoundtripModel CreateDefault()
    {
      var o = new RoundtripModel();
      o.B_val = true;
      o.I8_val = 8;
      o.I16_val = 1616;
      o.I32_val = 323232;
      o.I64_val = 6464646464L;
      o.F_val = 3.14f;
      o.D_val = 2.71828;
      o.S_val = "Hello DeukPack World";
      o.Bin_val = null;
      o.I32_list = new List<int>();
      o.S_list = new List<string>();
      o.S_i32_map = new Dictionary<string, int>();
      o.Nested = deuk.test.NestedStruct.CreateDefault();
      return o;
    }

    public override string ToString() { return ToString(""); }
    public string ToString(string indent)
    {
      var sb = new StringBuilder();
      var ci = indent + "  ";
      sb.Append("RoundtripModel {");
      sb.AppendLine();
      sb.Append(ci).Append("b_val: ").Append(this.B_val).AppendLine(",");
      sb.Append(ci).Append("i8_val: ").Append(this.I8_val).AppendLine(",");
      sb.Append(ci).Append("i16_val: ").Append(this.I16_val).AppendLine(",");
      sb.Append(ci).Append("i32_val: ").Append(this.I32_val).AppendLine(",");
      sb.Append(ci).Append("i64_val: ").Append(this.I64_val).AppendLine(",");
      sb.Append(ci).Append("f_val: ").Append(this.F_val).AppendLine(",");
      sb.Append(ci).Append("d_val: ").Append(this.D_val).AppendLine(",");
      sb.Append(ci).Append("s_val: ").Append(this.S_val).AppendLine(",");
      sb.Append(ci).Append("bin_val: [").Append(this.Bin_val?.Length ?? 0).AppendLine(" bytes],");
      sb.Append(ci).Append("i32_list: [").Append(this.I32_list?.Count ?? 0).AppendLine(" items],");
      sb.Append(ci).Append("s_list: [").Append(this.S_list?.Count ?? 0).AppendLine(" items],");
      sb.Append(ci).Append("s_i32_map: {").Append(this.S_i32_map?.Count ?? 0).AppendLine(" pairs},");
      sb.Append(ci).Append("nested: ").Append(this.Nested?.ToString(ci) ?? "null").AppendLine(",");
      sb.Append(indent).Append("}");
      return sb.ToString();
    }

    // Schema metadata
    public static DpSchema GetSchema()
    {
      return SchemaInfo.Value;
    }

    private static readonly Lazy<DpSchema> SchemaInfo = new Lazy<DpSchema>(() =>
    {
      var schema = new DpSchema
      {
        Name = "RoundtripModel",
        Type = DpDefinitionKind.Struct,
        DocComment = null,
        Annotations = null,
        Fields = new Dictionary<int, DpFieldSchema>
        {
          { 1, new DpFieldSchema
            {
              Id = 1,
              Order = 0,
              Name = "b_val",
              Type = DpSchemaType.Bool,
              TypeName = "bool",
              Required = false,
              DefaultValue = "true",
              DocComment = null,
              Annotations = null
            }
 },
          { 2, new DpFieldSchema
            {
              Id = 2,
              Order = 1,
              Name = "i8_val",
              Type = DpSchemaType.Byte,
              TypeName = "int8",
              Required = false,
              DefaultValue = 8,
              DocComment = null,
              Annotations = null
            }
 },
          { 3, new DpFieldSchema
            {
              Id = 3,
              Order = 2,
              Name = "i16_val",
              Type = DpSchemaType.Int16,
              TypeName = "int16",
              Required = false,
              DefaultValue = 1616,
              DocComment = null,
              Annotations = null
            }
 },
          { 4, new DpFieldSchema
            {
              Id = 4,
              Order = 3,
              Name = "i32_val",
              Type = DpSchemaType.Int32,
              TypeName = "int32",
              Required = false,
              DefaultValue = 323232,
              DocComment = null,
              Annotations = null
            }
 },
          { 5, new DpFieldSchema
            {
              Id = 5,
              Order = 4,
              Name = "i64_val",
              Type = DpSchemaType.Int64,
              TypeName = "int64",
              Required = false,
              DefaultValue = 6464646464,
              DocComment = null,
              Annotations = null
            }
 },
          { 6, new DpFieldSchema
            {
              Id = 6,
              Order = 5,
              Name = "f_val",
              Type = DpSchemaType.Double,
              TypeName = "float",
              Required = false,
              DefaultValue = 3.14,
              DocComment = null,
              Annotations = null
            }
 },
          { 7, new DpFieldSchema
            {
              Id = 7,
              Order = 6,
              Name = "d_val",
              Type = DpSchemaType.Double,
              TypeName = "double",
              Required = false,
              DefaultValue = 2.71828,
              DocComment = null,
              Annotations = null
            }
 },
          { 8, new DpFieldSchema
            {
              Id = 8,
              Order = 7,
              Name = "s_val",
              Type = DpSchemaType.String,
              TypeName = "string",
              Required = false,
              DefaultValue = "Hello DeukPack World",
              DocComment = null,
              Annotations = null
            }
 },
          { 9, new DpFieldSchema
            {
              Id = 9,
              Order = 8,
              Name = "bin_val",
              Type = DpSchemaType.Binary,
              TypeName = "binary",
              Required = false,
              DefaultValue = null,
              DocComment = null,
              Annotations = null
            }
 },
          { 10, new DpFieldSchema
            {
              Id = 10,
              Order = 9,
              Name = "i32_list",
              Type = DpSchemaType.List,
              TypeName = "int32",
              Required = false,
              DefaultValue = null,
              DocComment = null,
              Annotations = null
            }
 },
          { 11, new DpFieldSchema
            {
              Id = 11,
              Order = 10,
              Name = "s_list",
              Type = DpSchemaType.List,
              TypeName = "string",
              Required = false,
              DefaultValue = null,
              DocComment = null,
              Annotations = null
            }
 },
          { 12, new DpFieldSchema
            {
              Id = 12,
              Order = 11,
              Name = "s_i32_map",
              Type = DpSchemaType.Map,
              TypeName = "map<string, int32>",
              Required = false,
              DefaultValue = null,
              DocComment = null,
              Annotations = null
            }
 },
          { 13, new DpFieldSchema
            {
              Id = 13,
              Order = 12,
              Name = "nested",
              Type = DpSchemaType.Struct,
              TypeName = "NestedStruct",
              Required = false,
              DefaultValue = null,
              DocComment = null,
              Annotations = null
            }
 },
        }
      };
      return schema;
    });

  }


// Autogenerated by DeukPack v1.4.0 | https://deukpack.app
// Powered by DeukPack — Universal IDL Gateway for AI & Unity
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//  @generated

  [System.Serializable]
  public partial class NestedStruct : IDeukPack
  {

    public string Inner_val { get; set; } = "inner";
    public List<int> Numbers { get; set; }

    public static class FieldId
    {
      public const int Inner_val = 1;
      public const int Numbers = 2;
    }
    // 기본값 정적 노출 (enum/구조체 공통, 리플렉션 없이 조회)
    public static string Default_Inner_val => "inner";

    // Serialization methods
    public void Write(DpProtocol oprot) => Write(oprot, null, null);

    public void Write(DpProtocol oprot, ICollection<int>? fieldIds, Dictionary<int, object>? overrides = null)
    {
      if (fieldIds != null && fieldIds.Count == 0) return;
      DpRecord struc = new DpRecord("NestedStruct", 2);
      oprot.WriteStructBegin(struc);
      // field 1: inner_val
      if (fieldIds == null || fieldIds.Contains(1))
      {
        var _v1 = (overrides != null && overrides.TryGetValue(1, out var _o1)) ? (string)_o1 : this.Inner_val;
        if (_v1 != "inner")
        {
          DpColumn field = new DpColumn("inner_val", DpWireType.String, 1);
          oprot.WriteFieldBegin(field);
          DeukPackSerializer.WriteValue(oprot, DpWireType.String, _v1);
          oprot.WriteFieldEnd();
        }
      }
      // field 2: numbers
      if (fieldIds == null || fieldIds.Contains(2))
      {
        var _v2 = (overrides != null && overrides.TryGetValue(2, out var _o2)) ? (List<int>)_o2 : this.Numbers;
        if (_v2 != null)
        {
          DpColumn field = new DpColumn("numbers", DpWireType.List, 2);
          oprot.WriteFieldBegin(field);
          DeukPackSerializer.WriteList<int>(oprot, DpWireType.Int32, _v2);
          oprot.WriteFieldEnd();
        }
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public void Read(DpProtocol iprot)
    {
      this.Inner_val = "inner";
      this.Numbers = new List<int>();
      DpColumn field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == DpWireType.Stop)
        {
          break;
        }
        if (field.ID == 0 && !string.IsNullOrEmpty(field.Name))
        {
          if (field.Name == "inner_val") field.ID = 1;
          else           if (field.Name == "numbers") field.ID = 2;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == DpWireType.String || field.Type == DpWireType.Void)
            {
              this.Inner_val = (string)DeukPackSerializer.ReadValue(iprot, DpWireType.String, typeof(string))!;
            }
            else
            {
              DpProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == DpWireType.List || field.Type == DpWireType.Void)
            {
              this.Numbers = DeukPackSerializer.ReadList<int>(iprot, DpWireType.Int32);
            }
            else
            {
              DpProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default:
            DeukPack.Protocol.DeukPackSerializationWarnings.LogUnknownField("NestedStruct", field.ID, field.Name ?? "");
            DpProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();

    }

    // Clone method
    public NestedStruct Clone()
    {
      var clone = new NestedStruct();
      clone.Inner_val = this.Inner_val;
      clone.Numbers = this.Numbers != null ? (this.Numbers.Select(item => item).ToList()) : null!;
      return clone;
    }

    // Explicit interface implementation
    object IDeukPack.Clone()
    {
      return this.Clone();
    }

    // CreateDefault: recursive default instance
    public static NestedStruct CreateDefault()
    {
      var o = new NestedStruct();
      o.Inner_val = "inner";
      o.Numbers = new List<int>();
      return o;
    }

    public override string ToString() { return ToString(""); }
    public string ToString(string indent)
    {
      var sb = new StringBuilder();
      var ci = indent + "  ";
      sb.Append("NestedStruct {");
      sb.AppendLine();
      sb.Append(ci).Append("inner_val: ").Append(this.Inner_val).AppendLine(",");
      sb.Append(ci).Append("numbers: [").Append(this.Numbers?.Count ?? 0).AppendLine(" items],");
      sb.Append(indent).Append("}");
      return sb.ToString();
    }

    // Schema metadata
    public static DpSchema GetSchema()
    {
      return SchemaInfo.Value;
    }

    private static readonly Lazy<DpSchema> SchemaInfo = new Lazy<DpSchema>(() =>
    {
      var schema = new DpSchema
      {
        Name = "NestedStruct",
        Type = DpDefinitionKind.Struct,
        DocComment = null,
        Annotations = null,
        Fields = new Dictionary<int, DpFieldSchema>
        {
          { 1, new DpFieldSchema
            {
              Id = 1,
              Order = 0,
              Name = "inner_val",
              Type = DpSchemaType.String,
              TypeName = "string",
              Required = false,
              DefaultValue = "inner",
              DocComment = null,
              Annotations = null
            }
 },
          { 2, new DpFieldSchema
            {
              Id = 2,
              Order = 1,
              Name = "numbers",
              Type = DpSchemaType.List,
              TypeName = "int32",
              Required = false,
              DefaultValue = null,
              DocComment = null,
              Annotations = null
            }
 },
        }
      };
      return schema;
    });

  }


// Autogenerated by DeukPack v1.4.0 | https://deukpack.app
// Powered by DeukPack — Universal IDL Gateway for AI & Unity
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//  @generated

  [System.Serializable]
  public partial class EnumModel : IDeukPack
  {

    public deuk.test.TestEnum E_val { get; set; } = deuk.test.TestEnum.Beta;

    public static class FieldId
    {
      public const int E_val = 1;
    }
    // 기본값 정적 노출 (enum/구조체 공통, 리플렉션 없이 조회)
    public static deuk.test.TestEnum Default_E_val => deuk.test.TestEnum.Beta;

    // Serialization methods
    public void Write(DpProtocol oprot) => Write(oprot, null, null);

    public void Write(DpProtocol oprot, ICollection<int>? fieldIds, Dictionary<int, object>? overrides = null)
    {
      if (fieldIds != null && fieldIds.Count == 0) return;
      DpRecord struc = new DpRecord("EnumModel", 1);
      oprot.WriteStructBegin(struc);
      // field 1: e_val
      if (fieldIds == null || fieldIds.Contains(1))
      {
        var _v1 = (overrides != null && overrides.TryGetValue(1, out var _o1)) ? (deuk.test.TestEnum)_o1 : this.E_val;
        if (_v1 != deuk.test.TestEnum.Beta)
        {
          DpColumn field = new DpColumn("e_val", DpWireType.Int32, 1);
          oprot.WriteFieldBegin(field);
          DeukPackSerializer.WriteValue(oprot, DpWireType.Int32, _v1);
          oprot.WriteFieldEnd();
        }
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public void Read(DpProtocol iprot)
    {
      this.E_val = deuk.test.TestEnum.Beta;
      DpColumn field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == DpWireType.Stop)
        {
          break;
        }
        if (field.ID == 0 && !string.IsNullOrEmpty(field.Name))
        {
          if (field.Name == "e_val") field.ID = 1;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == DpWireType.Int32 || field.Type == DpWireType.Void)
            {
              this.E_val = (deuk.test.TestEnum)DeukPackSerializer.ReadValue(iprot, DpWireType.Int32, typeof(deuk.test.TestEnum))!;
            }
            else
            {
              DpProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default:
            DeukPack.Protocol.DeukPackSerializationWarnings.LogUnknownField("EnumModel", field.ID, field.Name ?? "");
            DpProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();

    }

    // Clone method
    public EnumModel Clone()
    {
      var clone = new EnumModel();
      clone.E_val = this.E_val;
      return clone;
    }

    // Explicit interface implementation
    object IDeukPack.Clone()
    {
      return this.Clone();
    }

    // CreateDefault: recursive default instance
    public static EnumModel CreateDefault()
    {
      var o = new EnumModel();
      o.E_val = deuk.test.TestEnum.Beta;
      return o;
    }

    public override string ToString() { return ToString(""); }
    public string ToString(string indent)
    {
      var sb = new StringBuilder();
      var ci = indent + "  ";
      sb.Append("EnumModel {");
      sb.AppendLine();
      sb.Append(ci).Append("e_val: ").Append(this.E_val.ToString()).AppendLine(",");
      sb.Append(indent).Append("}");
      return sb.ToString();
    }

    // Schema metadata
    public static DpSchema GetSchema()
    {
      return SchemaInfo.Value;
    }

    private static readonly Lazy<DpSchema> SchemaInfo = new Lazy<DpSchema>(() =>
    {
      var schema = new DpSchema
      {
        Name = "EnumModel",
        Type = DpDefinitionKind.Struct,
        DocComment = null,
        Annotations = null,
        Fields = new Dictionary<int, DpFieldSchema>
        {
          { 1, new DpFieldSchema
            {
              Id = 1,
              Order = 0,
              Name = "e_val",
              Type = DpSchemaType.Enum,
              TypeName = "TestEnum",
              Required = false,
              DefaultValue = "Beta",
              DocComment = null,
              Annotations = null
            }
 },
        }
      };
      return schema;
    });

  }


}
