/**
 * Autogenerated by DeukPack v1.0.0
 * @generated
 */

/** @generated */
export interface DemoPoint {
  x?: number;
  y?: number;
}

/** Field IDs for DemoPoint. @generated */
export const DemoPoint_FieldId = {
  X: 1,
  Y: 2,
} as const;

/** @generated */
export interface DemoUser {
  id?: number;
  name?: string;
  home?: DemoPoint;
}

/** Field IDs for DemoUser. @generated */
export const DemoUser_FieldId = {
  Id: 1,
  Name: 2,
  Home: 3,
} as const;

/** @generated */
export interface UserRecord {
  id?: number;
  displayName?: string;
  level?: number;
  avatarUrl?: string;
}

/** Field IDs for UserRecord. @generated */
export const UserRecord_FieldId = {
  Id: 1,
  DisplayName: 2,
  Level: 3,
  AvatarUrl: 4,
} as const;

/** @generated */
export interface UserBase {
  id?: number;
  tag?: string;
}

/** Field IDs for UserBase. @generated */
export const UserBase_FieldId = {
  Id: 1,
  Tag: 2,
} as const;

/** @generated */
export interface UserFull {
  id?: number;
  tag?: string;
  level?: number;
}

/** Field IDs for UserFull. @generated */
export const UserFull_FieldId = {
  Id: 1,
  Tag: 2,
  Level: 3,
} as const;
