package @@JAVA_PACKAGE@@;

import java.io.*;
import java.nio.charset.StandardCharsets;

/**
 * DeukPack Compact Protocol for Java (Thrift Compact Compatible)
 * Autogenerated by DeukPack v@@DEUKPACK_VERSION@@
 * @generated
 */
public class DpCompactProtocol implements DpProtocol {
    private final InputStream input;
    private final OutputStream output;

    private static final int MAX_SAFE_LENGTH = 10 * 1024 * 1024;
    private static final int MAX_RECURSION_DEPTH = 64;
    private int recursionDepth = 0;

    private short lastFieldId = 0;
    private final java.util.Stack<Short> lastFieldIdStack = new java.util.Stack<>();

    public DpCompactProtocol(InputStream input, OutputStream output) {
        this.input = input;
        this.output = output;
    }

    @Override public void writeMessageBegin(DpMessage msg) { writeByte((byte)0x82); writeByte((byte)((msg.Type << 5) | 1)); writeVarint32(msg.SeqID); writeString(msg.Name); }
    @Override public void writeMessageEnd() {}
    @Override public void writeStructBegin(DpRecord rec) { lastFieldIdStack.push(lastFieldId); lastFieldId = 0; }
    @Override public void writeStructEnd() { lastFieldId = lastFieldIdStack.pop(); }

    @Override public void writeFieldBegin(DpColumn col) {
        if (col.Type == DpWireType.Bool) { /* Special handling in writeBool */ }
        else { writeFieldBeginInternal(col, (byte)-1); }
    }

    private void writeFieldBeginInternal(DpColumn col, byte typeOverride) {
        byte type = typeOverride == -1 ? getCompactType(col.Type) : typeOverride;
        if (col.ID > lastFieldId && col.ID - lastFieldId <= 15) {
            writeByte((byte)((col.ID - lastFieldId) << 4 | type));
        } else {
            writeByte(type);
            writeI16(col.ID);
        }
        lastFieldId = col.ID;
    }

    @Override public void writeFieldEnd() {}
    @Override public void writeFieldStop() { writeByte((byte)0); }

    @Override public void writeMapBegin(DpDict dict) { if (dict.Count == 0) writeByte((byte)0); else { writeVarint32(dict.Count); writeByte((byte)(getCompactType(dict.KeyType) << 4 | getCompactType(dict.ValueType))); } }
    @Override public void writeMapEnd() {}
    @Override public void writeListBegin(DpList list) { if (list.Count < 15) writeByte((byte)(list.Count << 4 | getCompactType(list.ElementType))); else { writeByte((byte)(0xF0 | getCompactType(list.ElementType))); writeVarint32(list.Count); } }
    @Override public void writeListEnd() {}
    @Override public void writeSetBegin(DpSet set) { writeListBegin(new DpList(set.ElementType, set.Count)); }
    @Override public void writeSetEnd() { writeListEnd(); }

    @Override public void writeBool(boolean v) { /* Compact bool is normally in field tag, here we use simple byte for standalone */ writeByte(v ? (byte)1 : (byte)2); }
    @Override public void writeByte(byte v) { try { output.write(v); } catch (IOException e) { throw new RuntimeException(e); } }
    @Override public void writeI16(short v) { writeVarint32(intToZigZag(v)); }
    @Override public void writeI32(int v) { writeVarint32(intToZigZag(v)); }
    @Override public void writeI64(long v) { writeVarint64(longToZigZag(v)); }
    @Override public void writeDouble(double v) { long bits = Double.doubleToLongBits(v); for(int i=0; i<8; i++) { writeByte((byte)(bits & 0xFF)); bits >>= 8; } }
    @Override public void writeString(String v) { byte[] b = v.getBytes(StandardCharsets.UTF_8); writeVarint32(b.length); try { output.write(b); } catch (IOException e) { throw new RuntimeException(e); } }
    @Override public void writeBinary(byte[] v) { writeVarint32(v.length); try { output.write(v); } catch (IOException e) { throw new RuntimeException(e); } }

    private int intToZigZag(int n) { return (n << 1) ^ (n >> 31); }
    private long longToZigZag(long n) { return (n << 1) ^ (n >> 63); }
    private void writeVarint32(int n) { while ((n & ~0x7F) != 0) { writeByte((byte)((n & 0x7F) | 0x80)); n >>>= 7; } writeByte((byte)n); }
    private void writeVarint64(long n) { while ((n & ~0x7F) != 0) { writeByte((byte)((n & 0x7F) | 0x80)); n >>>= 7; } writeByte((byte)n); }

    @Override public DpMessage readMessageBegin() { byte sig = readByte(); if (sig != (byte)0x82) throw new RuntimeException("Bad sig"); byte ver = readByte(); return new DpMessage(readString(), (byte)((ver >> 5) & 0x7), readVarint32()); }
    @Override public void readMessageEnd() {}
    @Override public DpRecord readStructBegin() { if (++recursionDepth > MAX_RECURSION_DEPTH) throw new RuntimeException("Depth"); lastFieldIdStack.push(lastFieldId); lastFieldId = 0; return new DpRecord(); }
    @Override public void readStructEnd() { lastFieldId = lastFieldIdStack.pop(); recursionDepth--; }

    @Override public DpColumn readFieldBegin() {
        byte b = readByte(); if (b == 0) return new DpColumn("", DpWireType.Stop, (short)0);
        short modifier = (short)((b & 0xF0) >> 4);
        short id; if (modifier == 0) id = readI16(); else id = (short)(lastFieldId + modifier);
        lastFieldId = id; byte type = (byte)(b & 0x0F);
        return new DpColumn("", fromCompactType(type), id);
    }
    @Override public void readFieldEnd() {}

    @Override public boolean readBool() { byte b = readByte(); return b == 1; }
    @Override public byte readByte() { try { int b = input.read(); if (b == -1) throw new EOFException(); return (byte)b; } catch (IOException e) { throw new RuntimeException(e); } }
    @Override public short readI16() { return (short)zigZagToInt(readVarint32()); }
    @Override public int readI32() { return zigZagToInt(readVarint32()); }
    @Override public long readI64() { return zigZagToLong(readVarint64()); }
    @Override public double readDouble() { long bits = 0; for(int i=0; i<8; i++) bits |= ((long)(readByte() & 0xFF) << (i*8)); return Double.longBitsToDouble(bits); }
    @Override public String readString() { int len = readVarint32(); if (len < 0 || len > MAX_SAFE_LENGTH) throw new RuntimeException("Len"); byte[] b = new byte[len]; readAll(b); return new String(b, StandardCharsets.UTF_8); }
    @Override public byte[] readBinary() { int len = readVarint32(); if (len < 0 || len > MAX_SAFE_LENGTH) throw new RuntimeException("Len"); byte[] b = new byte[len]; readAll(b); return b; }

    private int zigZagToInt(int n) { return (n >>> 1) ^ -(n & 1); }
    private long zigZagToLong(long n) { return (n >>> 1) ^ -(n & 1); }
    private int readVarint32() { int res = 0, shift = 0; while (true) { byte b = readByte(); res |= (b & 0x7F) << shift; if ((b & 0x80) == 0) break; shift += 7; } return res; }
    private long readVarint64() { long res = 0; int shift = 0; while (true) { byte b = readByte(); res |= (long)(b & 0x7F) << shift; if ((b & 0x80) == 0) break; shift += 7; } return res; }
    private void readAll(byte[] b) { int off = 0; while (off < b.length) { try { int n = input.read(b, off, b.length - off); if (n == -1) throw new EOFException(); off += n; } catch (IOException e) { throw new RuntimeException(e); } } }

    private byte getCompactType(DpWireType t) {
        switch(t) {
            case Stop: return 0; case Bool: return 1; case Byte: return 3; case Int16: return 4;
            case Int32: return 5; case Int64: return 6; case Double: return 7; case String: return 8;
            case List: return 9; case Set: return 10; case Map: return 11; case Struct: return 12;
            default: return 12;
        }
    }
    private DpWireType fromCompactType(byte t) {
        switch(t) {
            case 0: return DpWireType.Stop; case 1: case 2: return DpWireType.Bool;
            case 3: return DpWireType.Byte; case 4: return DpWireType.Int16;
            case 5: return DpWireType.Int32; case 6: return DpWireType.Int64;
            case 7: return DpWireType.Double; case 8: return DpWireType.String;
            case 9: return DpWireType.List; case 10: return DpWireType.Set;
            case 11: return DpWireType.Map; case 12: return DpWireType.Struct;
            default: return DpWireType.Void;
        }
    }

    @Override public void skip(DpWireType type) { /* ... skip logic ... */ }
}
