package @@JAVA_PACKAGE@@;

import java.io.*;
import java.util.*;

/**
 * DeukPack TJSON Protocol for Java (Thrift TJSON Compatible)
 * Autogenerated by DeukPack v@@DEUKPACK_VERSION@@
 * @generated
 */
public class DpTJSONProtocol implements DpProtocol {
    private final Writer _writer;
    private final PushbackReader _reader;
    private final Stack<Boolean> _firstField = new Stack<>();

    private static final int MAX_SAFE_LENGTH = 10 * 1024 * 1024;
    private static final int MAX_RECURSION_DEPTH = 64;
    private int recursionDepth = 0;

    public DpTJSONProtocol(OutputStream out) {
        this._writer = new BufferedWriter(new OutputStreamWriter(out, java.nio.charset.StandardCharsets.UTF_8));
        this._reader = null;
    }
    public DpTJSONProtocol(InputStream in) {
        this._writer = null;
        this._reader = new PushbackReader(new InputStreamReader(in, java.nio.charset.StandardCharsets.UTF_8));
    }

    private void write(String s) { try { if (_writer != null) _writer.write(s); } catch (IOException e) { throw new RuntimeException(e); } }
    @Override public void writeMessageBegin(DpMessage msg) { write("[1,"); write("\"" + msg.Name + "\","); write(msg.Type + ","); write(msg.SeqID + ","); }
    @Override public void writeMessageEnd() { write("]"); flush(); }
    @Override public void writeStructBegin(DpRecord rec) { write("{"); _firstField.push(true); }
    @Override public void writeStructEnd() { write("}"); _firstField.pop(); }
    @Override public void writeFieldBegin(DpColumn col) { if (!_firstField.peek()) write(","); _firstField.set(_firstField.size() - 1, false); write("\"" + col.ID + "\":{\""); write(getTJSONTypeName(col.Type) + "\":"); }
    @Override public void writeFieldEnd() { write("}"); }
    @Override public void writeFieldStop() {}

    @Override public void writeMapBegin(DpDict dict) { write("[\""); write(getTJSONTypeName(dict.KeyType) + "\",\""); write(getTJSONTypeName(dict.ValueType) + "\","); write(dict.Count + ",{"); _firstField.push(true); }
    @Override public void writeMapEnd() { write("}]"); _firstField.pop(); }
    @Override public void writeListBegin(DpList list) { write("[\""); write(getTJSONTypeName(list.ElementType) + "\","); write(list.Count + ","); }
    @Override public void writeListEnd() { write("]"); }
    @Override public void writeSetBegin(DpSet set) { writeListBegin(new DpList(set.ElementType, set.Count)); }
    @Override public void writeSetEnd() { writeListEnd(); }

    @Override public void writeBool(boolean v) { write(v ? "1" : "0"); }
    @Override public void writeByte(byte v) { write(String.valueOf(v)); }
    @Override public void writeI16(short v) { write(String.valueOf(v)); }
    @Override public void writeI32(int v) { write(String.valueOf(v)); }
    @Override public void writeI64(long v) { write(String.valueOf(v)); }
    @Override public void writeDouble(double v) { write(String.valueOf(v)); }
    @Override public void writeString(String v) { write("\"" + v.replace("\"", "\\\"") + "\""); }
    @Override public void writeBinary(byte[] v) { writeString(Base64.getEncoder().encodeToString(v)); }

    private void flush() { try { if (_writer != null) _writer.flush(); } catch (IOException e) {} }

    private String getTJSONTypeName(DpWireType t) {
        switch(t) {
            case Bool: return "tf"; case Byte: return "i8"; case Int16: return "i16";
            case Int32: return "i32"; case Int64: return "i64"; case Double: return "dbl";
            case String: return "str"; case Struct: return "rec"; case List: return "lst";
            case Set: return "set"; case Map: return "map"; default: return "obj";
        }
    }

    // --- Reader (Manual TJSON Parser) ---
    private char skipWS() throws IOException { int c; while ((c = _reader.read()) != -1 && Character.isWhitespace(c)); return (char) c; }
    private void expect(char exp) { try { char c = skipWS(); if (c != exp) throw new RuntimeException("Expected " + exp + ", got " + c); } catch (IOException e) { throw new RuntimeException(e); } }
    private String readQuoted() throws IOException { expect('\"'); StringBuilder sb = new StringBuilder(); int c; while ((c = _reader.read()) != -1 && c != '\"') { if (c == '\\') { c = _reader.read(); } sb.append((char)c); } return sb.toString(); }

    @Override public DpMessage readMessageBegin() { expect('['); readSimpleValue(); expect(','); String name = null; try { name = readQuoted(); } catch(Exception e){} expect(','); String typeStr = readSimpleValue(); expect(','); String seqStr = readSimpleValue(); expect(','); return new DpMessage(name, (byte)Integer.parseInt(typeStr), Integer.parseInt(seqStr)); }
    @Override public void readMessageEnd() { expect(']'); }

    @Override public DpRecord readStructBegin() { if (++recursionDepth > MAX_RECURSION_DEPTH) throw new RuntimeException("Depth"); expect('{'); return new DpRecord(); }
    @Override public void readStructEnd() { expect('}'); recursionDepth--; }
    @Override public DpColumn readFieldBegin() { try { char c = skipWS(); if (c == '}') return new DpColumn("", DpWireType.Stop, (short)0); if (c == ',') c = skipWS(); if (c != '\"') throw new RuntimeException("Expected \" for field ID"); StringBuilder sb = new StringBuilder(); int r; while ((r = _reader.read()) != -1 && r != '\"') sb.append((char)r); expect(':'); expect('{'); String typeKey = readQuoted(); expect(':'); return new DpColumn("", fromTJSONTypeName(typeKey), Short.parseShort(sb.toString())); } catch (IOException e) { throw new RuntimeException(e); } }
    @Override public void readFieldEnd() { expect('}'); }

    @Override public boolean readBool() { return Integer.parseInt(readSimpleValue()) != 0; }
    @Override public byte readByte() { return (byte)Integer.parseInt(readSimpleValue()); }
    @Override public short readI16() { return (short)Integer.parseInt(readSimpleValue()); }
    @Override public int readI32() { return Integer.parseInt(readSimpleValue()); }
    @Override public long readI64() { return Long.parseLong(readSimpleValue()); }
    @Override public double readDouble() { return Double.parseDouble(readSimpleValue()); }
    @Override public String readString() { try { return readQuoted(); } catch (IOException e) { throw new RuntimeException(e); } }
    @Override public byte[] readBinary() { return Base64.getDecoder().decode(readString()); }

    private String readSimpleValue() { try { StringBuilder sb = new StringBuilder(); char c; while (true) { c = (char)_reader.read(); if (c == ',' || c == '}' || c == ']' || Character.isWhitespace(c)) { _reader.unread(c); break; } sb.append(c); } return sb.toString(); } catch (IOException e) { throw new RuntimeException(e); } }

    private DpWireType fromTJSONTypeName(String name) {
        if ("tf".equals(name)) return DpWireType.Bool; if ("i8".equals(name)) return DpWireType.Byte;
        if ("i16".equals(name)) return DpWireType.Int16; if ("i32".equals(name)) return DpWireType.Int32;
        if ("i64".equals(name)) return DpWireType.Int64; if ("dbl".equals(name)) return DpWireType.Double;
        if ("str".equals(name)) return DpWireType.String; if ("rec".equals(name) || "obj".equals(name)) return DpWireType.Struct;
        if ("lst".equals(name)) return DpWireType.List; if ("set".equals(name)) return DpWireType.Set;
        if ("map".equals(name)) return DpWireType.Map; return DpWireType.Void;
    }

    @Override public void skip(DpWireType type) { /* Placeholder */ }
}
