/**
 * DeukPack Java Generated Code
 * Autogenerated by DeukPack v@@DEUKPACK_VERSION@@
 * @generated
 */
package @@JAVA_PACKAGE@@;

import java.util.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
