/**
 * DeukPack Binary Protocol for C++
 * Autogenerated by DeukPack v1.4.0
 * @generated
 */
#pragma once
#include "DpProtocol.h"
#include <iostream>
#include <algorithm>

namespace deuk {

class DpBinaryProtocol : public DpProtocol {
private:
  std::istream* input{nullptr};
  std::ostream* output{nullptr};
  static constexpr int32 MAX_SAFE_LENGTH = 10 * 1024 * 1024; // 10MB
  static constexpr int32 MAX_ELEMENT_COUNT = 1000000; // 1M elements
  static constexpr int32 MAX_RECURSION_DEPTH = 64;
  int32 recursionDepth{0};

public:
  DpBinaryProtocol(std::istream* is, std::ostream* os) : input(is), output(os) {}
  explicit DpBinaryProtocol(std::istream* is) : input(is), output(nullptr) {}
  explicit DpBinaryProtocol(std::ostream* os) : input(nullptr), output(os) {}

  void WriteMessageBegin(const DpMessage& message) override {
    WriteString(message.Name);
    WriteByte(static_cast<uint8>(message.Type));
    WriteI32(message.SeqID);
  }
  void WriteMessageEnd() override {}

  void WriteStructBegin(const DpRecord&) override {}
  void WriteStructEnd() override {}

  void WriteFieldBegin(const DpColumn& column) override {
    WriteByte(static_cast<uint8>(column.Type));
    WriteI16(column.ID);
  }
  void WriteFieldEnd() override {}
  void WriteFieldStop() override {
    WriteByte(static_cast<uint8>(DpWireType::Stop));
  }

  void WriteMapBegin(const DpDict& dict) override {
    WriteByte(static_cast<uint8>(dict.KeyType));
    WriteByte(static_cast<uint8>(dict.ValueType));
    WriteI32(dict.Count);
  }
  void WriteMapEnd() override {}

  void WriteListBegin(const DpList& list) override {
    WriteByte(static_cast<uint8>(list.ElementType));
    WriteI32(list.Count);
  }
  void WriteListEnd() override {}

  void WriteSetBegin(const DpSet& set) override {
    WriteByte(static_cast<uint8>(set.ElementType));
    WriteI32(set.Count);
  }
  void WriteSetEnd() override {}

  void WriteBool(bool value) override {
    WriteByte(value ? 1 : 0);
  }

  void WriteByte(uint8 value) override {
    if (output) output->put(static_cast<char>(value));
  }

  void WriteI16(int16 value) override {
    WriteByte(static_cast<uint8>((value >> 8) & 0xFF));
    WriteByte(static_cast<uint8>(value & 0xFF));
  }

  void WriteI32(int32 value) override {
    WriteByte(static_cast<uint8>((value >> 24) & 0xFF));
    WriteByte(static_cast<uint8>((value >> 16) & 0xFF));
    WriteByte(static_cast<uint8>((value >> 8) & 0xFF));
    WriteByte(static_cast<uint8>(value & 0xFF));
  }

  void WriteI64(int64 value) override {
    for (int i = 7; i >= 0; --i) {
        WriteByte(static_cast<uint8>((value >> (i * 8)) & 0xFF));
    }
  }

  void WriteDouble(float64 value) override {
    union { float64 d; int64 i; } u;
    u.d = value;
    WriteI64(u.i);
  }

  void WriteString(const std::string& value) override {
    WriteI32(static_cast<int32>(value.length()));
    if (output) output->write(value.data(), value.length());
  }

  void WriteBinary(const std::string& value) override {
    WriteString(value);
  }

  // --- Read ---

  DpMessage ReadMessageBegin() override {
    std::string name = ReadString();
    uint8 type = ReadByte();
    int32 seq = ReadI32();
    return {name, static_cast<DpMessageType>(type), seq};
  }
  void ReadMessageEnd() override {}

  DpRecord ReadStructBegin() override {
    if (++recursionDepth > MAX_RECURSION_DEPTH) {
        throw std::runtime_error("Max recursion depth exceeded");
    }
    return {};
  }
  void ReadStructEnd() override {
    if (--recursionDepth < 0) recursionDepth = 0;
  }

  DpColumn ReadFieldBegin() override {
    uint8 type = ReadByte();
    if (type == static_cast<uint8>(DpWireType::Stop)) {
      return {"", DpWireType::Stop, 0};
    }
    int16 id = ReadI16();
    return {"", static_cast<DpWireType>(type), id};
  }
  void ReadFieldEnd() override {}

  DpDict ReadMapBegin() override {
    uint8 kt = ReadByte();
    uint8 vt = ReadByte();
    int32 count = ReadI32();
    if (count < 0 || count > MAX_ELEMENT_COUNT) throw std::runtime_error("Invalid map count");
    return {static_cast<DpWireType>(kt), static_cast<DpWireType>(vt), count};
  }
  void ReadMapEnd() override {}

  DpList ReadListBegin() override {
    uint8 et = ReadByte();
    int32 count = ReadI32();
    if (count < 0 || count > MAX_ELEMENT_COUNT) throw std::runtime_error("Invalid list count");
    return {static_cast<DpWireType>(et), count};
  }
  void ReadListEnd() override {}

  DpSet ReadSetBegin() override {
    uint8 et = ReadByte();
    int32 count = ReadI32();
    if (count < 0 || count > MAX_ELEMENT_COUNT) throw std::runtime_error("Invalid set count");
    return {static_cast<DpWireType>(et), count};
  }
  void ReadSetEnd() override {}

  bool ReadBool() override { return ReadByte() != 0; }
  uint8 ReadByte() override {
    if (!input) return 0;
    int c = input->get();
    if (c == EOF) return 0;
    return static_cast<uint8>(c);
  }
  int16 ReadI16() override {
    uint8 b1 = ReadByte();
    uint8 b2 = ReadByte();
    return static_cast<int16>((b1 << 8) | b2);
  }
  int32 ReadI32() override {
    uint32 b1 = ReadByte();
    uint32 b2 = ReadByte();
    uint32 b3 = ReadByte();
    uint32 b4 = ReadByte();
    return static_cast<int32>((b1 << 24) | (b2 << 16) | (b3 << 8) | b4);
  }
  int64 ReadI64() override {
    uint64 v = 0;
    for (int i = 0; i < 8; ++i) {
        v = (v << 8) | ReadByte();
    }
    return static_cast<int64>(v);
  }
  float64 ReadDouble() override {
    union { float64 d; int64 i; } u;
    u.i = ReadI64();
    return u.d;
  }
  std::string ReadString() override {
    int32 len = ReadI32();
    if (len == 0) return {};
    if (len < 0 || len > MAX_SAFE_LENGTH) {
        throw std::runtime_error("Invalid string/binary length: string too long or negative");
    }
    std::string s(len, '\0');
    if (input) input->read(&s[0], len);
    return s;
  }
  std::string ReadBinary() override { return ReadString(); }
};

} // namespace deuk
