#pragma once
#include "DpProtocol.h"
#include <sstream>
#include <iomanip>
#include <vector>
#include <string>
#include <stdexcept>
#include <algorithm>

namespace deuk {

/**
 * DeukPack JSON Protocol for C++ (Tagged JSON wire)
 * 0-dependency Recursive Descent Parser included.
 * Autogenerated by DeukPack v@@DEUKPACK_VERSION@@
 * @generated
 */
class DpJsonProtocol : public DpProtocol {
public:
    DpJsonProtocol(std::ostream* os) : _os(os), _is(nullptr) {}
    DpJsonProtocol(std::istream* is) : _os(nullptr), _is(is), _pos(0) {
        if (is) {
            std::stringstream ss;
            ss << is->rdbuf();
            _json = ss.str();
        }
    }

    // Writer Implementation
    void WriteMessageBegin(const DpMessage& msg) override {
        *_os << "[";
        WriteString(msg.Name);
        *_os << "," << (int)msg.Type << "," << msg.SeqID << ",";
    }
    void WriteMessageEnd() override { *_os << "]"; }

    void WriteStructBegin(const DpRecord&) override {
        *_os << "{";
        _firstField.push_back(true);
    }
    void WriteStructEnd() override {
        *_os << "}";
        _firstField.pop_back();
    }

    void WriteFieldBegin(const DpColumn& col) override {
        if (!_firstField.back()) *_os << ",";
        _firstField.back() = false;
        *_os << "\"" << col.ID << "\":";
    }
    void WriteFieldEnd() override {}
    void WriteFieldStop() override {}

    void WriteMapBegin(const DpDict&) override { *_os << "{\"map\":{"; _firstField.push_back(true); }
    void WriteMapEnd() override { *_os << "}}"; _firstField.pop_back(); }

    void WriteListBegin(const DpList&) override { *_os << "{\"lst\":["; _firstField.push_back(true); }
    void WriteListEnd() override { *_os << "]}"; _firstField.pop_back(); }

    void WriteSetBegin(const DpSet& s) override { WriteListBegin({s.ElementType, s.Count}); }
    void WriteSetEnd() override { WriteListEnd(); }

    void WriteBool(bool v) override { *_os << "{\"tf\":" << (v ? "true" : "false") << "}"; }
    void WriteByte(uint8 v) override { *_os << "{\"i32\":" << (int)v << "}"; }
    void WriteI16(int16 v) override { *_os << "{\"i32\":" << (int)v << "}"; }
    void WriteI32(int32 v) override { *_os << "{\"i32\":" << v << "}"; }
    void WriteI64(int64 v) override { *_os << "{\"i64\":\"" << v << "\"}"; }
    void WriteDouble(float64 v) override { *_os << "{\"dbl\":" << v << "}"; }
    void WriteString(const std::string& v) override {
        *_os << "{\"str\":\"" << Escape(v) << "\"}";
    }
    void WriteBinary(const std::string& v) override {
        // Placeholder, typically Base64
        *_os << "{\"str\":\"" << Escape(v) << "\"}";
    }

    // Reader Implementation
    DpMessage ReadMessageBegin() override {
        Expect('[');
        std::string name = ReadString();
        Expect(',');
        int type = (int)ReadDouble(); // JSON numbers are often parsed as double
        Expect(',');
        int seq = (int)ReadDouble();
        Expect(',');
        return {name, (DpMessageType)type, seq};
    }
    void ReadMessageEnd() override { Expect(']'); }

    DpRecord ReadStructBegin() override { SkipComma(); Expect('{'); return {}; }
    void ReadStructEnd() override { SkipWS(); if (_pos < _json.size() && _json[_pos] == '}') _pos++; }

    DpColumn ReadFieldBegin() override {
        SkipWS();
        if (Peek() == '}') return {"", DpWireType::Stop, 0};
        std::string idStr = ReadRawString();
        Expect(':');
        return {"", DpWireType::Void, (int16)std::stoi(idStr)};
    }
    void ReadFieldEnd() override {
        SkipWS();
        if (Peek() == ',') Consume();
    }

    DpDict ReadMapBegin() override {
        SkipComma();
        Expect('{'); ExpectRawString("map"); Expect(':'); Expect('{');
        // Count keys until '}'
        int count = 0;
        size_t savePos = _pos;
        try {
            SkipWS();
            if (Peek() != '}') {
                count++;
                ReadRawString(); Expect(':'); ReadValuePlaceholder(); // skip value
                while (Peek() == ',') {
                    Consume(); count++;
                    ReadRawString(); Expect(':'); ReadValuePlaceholder();
                }
            }
        } catch(...) {}
        _pos = savePos;
        _readMapKey = true;
        return {DpWireType::Void, DpWireType::Void, count};
    }
    void ReadMapEnd() override {
        _readMapKey = false;
        Expect('}'); Expect('}');
    }

    DpList ReadListBegin() override {
        SkipComma();
        Expect('{'); ExpectRawString("lst"); Expect(':'); Expect('[');
        // Count elements until ']'
        int count = 0;
        size_t savePos = _pos;
        try {
            SkipWS();
            if (Peek() != ']') {
                count++;
                ReadValuePlaceholder();
                while (Peek() == ',') {
                    Consume(); count++;
                    ReadValuePlaceholder();
                }
            }
        } catch(...) {}
        _pos = savePos;
        DpList l;
        l.ElementType = DpWireType::Void;
        l.Count = count;
        std::cerr << "ReadListBegin: pos=" << savePos << " count=" << count << std::endl;
        return l;
    }
    void ReadListEnd() override { Expect(']'); Expect('}'); }

    DpSet ReadSetBegin() override { DpList l = ReadListBegin(); return {l.ElementType, l.Count}; }
    void ReadSetEnd() override { ReadListEnd(); }

    bool ReadBool() override {
        SkipComma();
        Expect('{'); ExpectRawString("tf"); Expect(':');
        bool v;
        if (Peek() == 't') { std::string s = ReadRawString(); v = (s == "true"); }
        else if (Peek() == 'f') { std::string s = ReadRawString(); v = (s == "false"); }
        else { v = ReadRawBool(); }
        Expect('}');
        return v;
    }
    uint8 ReadByte() override { return (uint8)ReadI32(); }
    int16 ReadI16() override { return (int16)ReadI32(); }
    int32 ReadI32() override {
        SkipComma();
        Expect('{'); ExpectRawString("i32"); Expect(':'); int32 v = (int32)ReadRawNumber(); Expect('}'); return v;
    }
    int64 ReadI64() override {
        SkipComma();
        Expect('{'); ExpectRawString("i64"); Expect(':');
        int64 v;
        if (Peek() == '"') v = std::stoll(ReadRawString());
        else v = (int64)ReadRawNumber();
        Expect('}');
        return v;
    }
    float64 ReadDouble() override { SkipComma(); Expect('{'); ExpectRawString("dbl"); Expect(':'); float64 v = ReadRawNumber(); Expect('}'); return v; }
    std::string ReadString() override {
        SkipComma();
        SkipWS();
        if (Peek() == '"') {
            std::string s = ReadRawString();
            SkipWS();
            if (Peek() == ':') Consume();
            return s;
        }
        Expect('{'); ExpectRawString("str"); Expect(':'); std::string s = ReadRawString(); Expect('}'); return s;
    }
    std::string ReadBinary() override { return ReadString(); }

private:
    std::ostream* _os;
    std::istream* _is;
    std::string _json;
    size_t _pos;
    std::vector<bool> _firstField;

    void SkipWS() { while (_pos < _json.size() && isspace((unsigned char)_json[_pos])) _pos++; }
    void SkipComma() { 
        SkipWS(); 
        if (_pos < _json.size() && _json[_pos] == ',') { 
            // std::cerr << "SkipComma at pos " << _pos << std::endl;
            _pos++; 
            SkipWS(); 
        } 
    }
    char Peek() { SkipWS(); return _json[_pos]; }
    char Consume() { SkipWS(); char c = _json[_pos++]; return c; }
    void Expect(char c) { 
        char x = Consume();
        if (x != c) {
            std::cerr << "Read error at pos " << (_pos-1) << ": Expected '" << c << "' but got '" << x << "' (ASCII: " << (int)x << ")" << std::endl;
            std::cerr << "Context: " << _json.substr((_pos > 10 ? _pos - 10 : 0), 20) << std::endl;
            throw std::runtime_error(std::string("Expected ") + c); 
        }
    }
    void ExpectRawString(const std::string& s) { if (ReadRawString() != s) throw std::runtime_error("Expected key " + s); }

    std::string ReadRawString() {
        Expect('"');
        std::string res;
        while (_json[_pos] != '"') {
            if (_json[_pos] == '\\') _pos++; // Simple escape skip
            res += _json[_pos++];
        }
        Expect('"');
        return res;
    }

    double ReadRawNumber() {
        SkipWS();
        size_t next;
        double v = std::stod(_json.substr(_pos), &next);
        _pos += next;
        return v;
    }

    bool ReadRawBool() {
        SkipWS();
        if (_json.substr(_pos, 4) == "true") { _pos += 4; return true; }
        if (_json.substr(_pos, 5) == "false") { _pos += 5; return false; }
        throw std::runtime_error("Expected bool");
    }
    void ReadValuePlaceholder() {
        SkipWS();
        char c = Peek();
        if (c == '{') {
            Consume(); int depth = 1;
            while (depth > 0 && _pos < _json.size()) {
                char x = Consume();
                if (x == '{') depth++; else if (x == '}') depth--;
                else if (x == '"') {
                    while (_pos < _json.size() && _json[_pos] != '"') {
                        if (_json[_pos] == '\\') _pos++;
                        _pos++;
                    }
                    if (_pos < _json.size()) _pos++;
                }
            }
        } else if (c == '[') {
            Consume(); int depth = 1;
            while (depth > 0 && _pos < _json.size()) {
                char x = Consume();
                if (x == '[') depth++; else if (x == ']') depth--;
                else if (x == '"') {
                    while (_pos < _json.size() && _json[_pos] != '"') {
                        if (_json[_pos] == '\\') _pos++;
                        _pos++;
                    }
                    if (_pos < _json.size()) _pos++;
                }
            }
        } else if (c == '"') {
            ReadRawString();
        } else {
            while (_pos < _json.size() && _json[_pos] != ',' && _json[_pos] != ']' && _json[_pos] != '}') _pos++;
        }
    }

    std::string Escape(const std::string& s) {
        std::string res;
        for (char c : s) {
            if (c == '"') res += "\\\"";
            else if (c == '\\') res += "\\\\";
            else res += c;
        }
        return res;
    }
};

} // namespace deuk
