/**
 * DeukPack Protocol Interface for C++
 * Autogenerated by DeukPack v@@DEUKPACK_VERSION@@
 * @generated
 */
#pragma once
#include <cstdint>
#include <string>
#include <vector>

namespace deuk {

using int8 = std::int8_t;
using int16 = std::int16_t;
using int32 = std::int32_t;
using int64 = std::int64_t;
using uint8 = std::uint8_t;
using uint16 = std::uint16_t;
using uint32 = std::uint32_t;
using uint64 = std::uint64_t;
using float32 = float;
using float64 = double;

enum class DpWireType : uint8 {
  Stop = 0,
  Void = 1,
  Bool = 2,
  Byte = 3,
  Double = 4,
  Int16 = 6,
  Int32 = 8,
  Int64 = 10,
  String = 11,
  Struct = 12,
  Map = 13,
  Set = 14,
  List = 15,
};

enum class DpMessageType : uint8 {
  Call = 1,
  Reply = 2,
  Exception = 3,
  Oneway = 4,
};

struct DpRecord {
  std::string Name{};
  int32 Count{0};
};

struct DpMessage {
  std::string Name{};
  DpMessageType Type{};
  int32 SeqID{};
};

struct DpColumn {
  std::string Name{};
  DpWireType Type{};
  int16 ID{};
};

struct DpList {
  DpWireType ElementType{};
  int32 Count{};
};

struct DpSet {
  DpWireType ElementType{};
  int32 Count{};
};

struct DpDict {
  DpWireType KeyType{};
  DpWireType ValueType{};
  int32 Count{};
};

class DpProtocol {
public:
  virtual ~DpProtocol() = default;

  virtual void WriteMessageBegin(const DpMessage& message) = 0;
  virtual void WriteMessageEnd() = 0;
  virtual void WriteStructBegin(const DpRecord& record) = 0;
  virtual void WriteStructEnd() = 0;
  virtual void WriteFieldBegin(const DpColumn& column) = 0;
  virtual void WriteFieldEnd() = 0;
  virtual void WriteFieldStop() = 0;
  virtual void WriteMapBegin(const DpDict& dict) = 0;
  virtual void WriteMapEnd() = 0;
  virtual void WriteListBegin(const DpList& list) = 0;
  virtual void WriteListEnd() = 0;
  virtual void WriteSetBegin(const DpSet& set) = 0;
  virtual void WriteSetEnd() = 0;
  virtual void WriteBool(bool value) = 0;
  virtual void WriteByte(uint8 value) = 0;
  virtual void WriteI16(int16 value) = 0;
  virtual void WriteI32(int32 value) = 0;
  virtual void WriteI64(int64 value) = 0;
  virtual void WriteDouble(float64 value) = 0;
  virtual void WriteString(const std::string& value) = 0;
  virtual void WriteBinary(const std::string& value) = 0;

  virtual DpMessage ReadMessageBegin() = 0;
  virtual void ReadMessageEnd() = 0;
  virtual DpRecord ReadStructBegin() = 0;
  virtual void ReadStructEnd() = 0;
  virtual DpColumn ReadFieldBegin() = 0;
  virtual void ReadFieldEnd() = 0;
  virtual DpDict ReadMapBegin() = 0;
  virtual void ReadMapEnd() = 0;
  virtual DpList ReadListBegin() = 0;
  virtual void ReadListEnd() = 0;
  virtual DpSet ReadSetBegin() = 0;
  virtual void ReadSetEnd() = 0;
  virtual bool ReadBool() = 0;
  virtual uint8 ReadByte() = 0;
  virtual int16 ReadI16() = 0;
  virtual int32 ReadI32() = 0;
  virtual int64 ReadI64() = 0;
  virtual float64 ReadDouble() = 0;
  virtual std::string ReadString() = 0;
  virtual std::string ReadBinary() = 0;

  virtual void Skip(DpWireType type) {
    switch (type) {
      case DpWireType::Bool: ReadBool(); break;
      case DpWireType::Byte: ReadByte(); break;
      case DpWireType::Int16: ReadI16(); break;
      case DpWireType::Int32: ReadI32(); break;
      case DpWireType::Int64: ReadI64(); break;
      case DpWireType::Double: ReadDouble(); break;
      case DpWireType::String: ReadString(); break;
      case DpWireType::Struct:
        ReadStructBegin();
        while (true) {
          DpColumn f = ReadFieldBegin();
          if (f.Type == DpWireType::Stop) break;
          Skip(f.Type);
          ReadFieldEnd();
        }
        ReadStructEnd();
        break;
      case DpWireType::Map: {
        DpDict m = ReadMapBegin();
        for (int32 i = 0; i < m.Count; ++i) {
          Skip(m.KeyType);
          Skip(m.ValueType);
        }
        ReadMapEnd();
        break;
      }
      case DpWireType::Set: {
        DpSet s = ReadSetBegin();
        for (int32 i = 0; i < s.Count; ++i) {
          Skip(s.ElementType);
        }
        ReadSetEnd();
        break;
      }
      case DpWireType::List: {
        DpList l = ReadListBegin();
        for (int32 i = 0; i < l.Count; ++i) {
          Skip(l.ElementType);
        }
        ReadListEnd();
        break;
      }
      default: break;
    }
  }
};

class IDpSerializable {
public:
  virtual ~IDpSerializable() = default;
  virtual void Write(DpProtocol& oprot) const = 0;
  virtual void Read(DpProtocol& iprot) = 0;
};

} // namespace deuk
