/**
 * Autogenerated by DeukPack v@@DEUKPACK_VERSION@@
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * @generated
 */
#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <map>
#include <set>
#include <any>
#include <unordered_map>
#include "DpProtocol.h"

