/**
 * Generated by DeukPack MCP Generator
 * AI-Ready Interface Hub
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";

const server = new McpServer({
  name: "deukpack-mcp-server",
  version: "1.0.0",
});

// --- Service Implementation Registry ---
const serviceRegistry = new Map();

/**
 * Register a backend service implementation for MCP tools.
 * @param {string} serviceName - e.g. "GameService"
 * @param {object} instance - The service instance matching the IDL methods.
 */
export function registerService(serviceName, instance) {
  serviceRegistry.set(serviceName, instance);
}

// --- Resources (Data Structures) ---
// Resource: Hero_Ability
server.resource(
  "Hero_Ability",
  "deukpack://Hero_Ability",
  { description: "영웅의 능력치 정보" },
  async (uri) => ({
    contents: [{
      uri: uri.href,
      text: "Hero_Ability { strength: int32, intelligence: int32, agility: int32, grade: Grade }"
    }]
  })
);

// Resource: Hero_Weapon
server.resource(
  "Hero_Weapon",
  "deukpack://Hero_Weapon",
  { description: "영웅의 인벤토리 (Oneof 예제)" },
  async (uri) => ({
    contents: [{
      uri: uri.href,
      text: "Hero_Weapon { weapon_name: string, damage: int32 }"
    }]
  })
);

// Resource: Hero_Armor
server.resource(
  "Hero_Armor",
  "deukpack://Hero_Armor",
  { description: "Structure: Hero_Armor" },
  async (uri) => ({
    contents: [{
      uri: uri.href,
      text: "Hero_Armor { armor_name: string, defense: int32 }"
    }]
  })
);

// Resource: Hero
server.resource(
  "Hero",
  "deukpack://Hero",
  { description: "* 영웅의 서사시 (Hero Saga) - 실전형 복잡 구조 예제" },
  async (uri) => ({
    contents: [{
      uri: uri.href,
      text: "Hero { id: int32, name: string, role: Role, stats: Ability, primary_weapon: Weapon, main_armor: Armor, titles: string[] }"
    }]
  })
);

// Resource: QuestRequest
server.resource(
  "QuestRequest",
  "deukpack://QuestRequest",
  { description: "Structure: QuestRequest" },
  async (uri) => ({
    contents: [{
      uri: uri.href,
      text: "QuestRequest { hero_id: int32, location: string }"
    }]
  })
);

// Resource: QuestResponse
server.resource(
  "QuestResponse",
  "deukpack://QuestResponse",
  { description: "Structure: QuestResponse" },
  async (uri) => ({
    contents: [{
      uri: uri.href,
      text: "QuestResponse { success: bool, message: string, rewards: string[] }"
    }]
  })
);


// --- Tools (Service Methods) ---
// Tool: SagaService_EmbarkQuest
server.tool(
  "SagaService_EmbarkQuest",
  "* 퀘스트를 수락하고 서사시를 진행합니다.",
  {
    req: z.any(),
  },
  async (args) => {
    const instance = serviceRegistry.get("SagaService");
    if (!instance) {
      return { content: [{ type: "text", text: "Service SagaService is not registered on this MCP server." }] };
    }
    try {
      const params = [args.req];
      const result = await instance.EmbarkQuest(...params);
      return { content: [{ type: "text", text: JSON.stringify(result, null, 2) }] };
    } catch (err) {
      return { content: [{ type: "text", text: `Error calling SagaService.EmbarkQuest: ${err.message}` }] };
    }
  }
);


// --- Start Server ---
const transport = new StdioServerTransport();
await server.connect(transport);
console.error("DeukPack MCP Server started via stdio");
