/**
 * DeukPack Pack Protocol for C++ (Tagged LE binary)
 * Autogenerated by DeukPack v1.4.0
 * @generated
 */
#pragma once
#include "DpProtocol.h"
#include <iostream>
#include <algorithm>
#include <stack>
#include <stdexcept>

namespace deuk {

class DpPackProtocol : public DpProtocol {
private:
  std::istream* input{nullptr};
  std::ostream* output{nullptr};
  std::stack<int32> fieldCounts{};

public:
  enum class PackTag : uint8 {
    Null = 0, False = 1, True = 2, Int32 = 3, Int64 = 4, Double = 5, String = 6, Binary = 7, Array = 8, Map = 9, Object = 10
  };

  DpPackProtocol(std::istream* is, std::ostream* os) : input(is), output(os) {}
  explicit DpPackProtocol(std::istream* is) : input(is) {}
  explicit DpPackProtocol(std::ostream* os) : output(os) {}

  void WriteMessageBegin(const DpMessage& message) override {
    WriteTag(PackTag::Array);
    WriteRawI32(3);
    WriteString(message.Name);
    WriteByte(static_cast<uint8>(message.Type));
    WriteI32(message.SeqID);
  }
  void WriteMessageEnd() override {}

  void WriteStructBegin(const DpRecord& record) override {
    WriteTag(PackTag::Object);
    WriteRawI32(record.Count);
  }
  void WriteStructEnd() override {}

  void WriteTag(PackTag tag) {
    if (output) output->put(static_cast<char>(tag));
  }

  void WriteFieldBegin(const DpColumn& column) override {
    // Pack wire: key string (no tag)
    WriteRawString(column.Name);
  }
  void WriteFieldEnd() override {}
  void WriteFieldStop() override {}

  void WriteMapBegin(const DpDict& dict) override {
    WriteTag(PackTag::Map);
    WriteRawI32(dict.Count);
  }
  void WriteMapEnd() override {}

  void WriteListBegin(const DpList& list) override {
    WriteTag(PackTag::Array);
    WriteRawI32(list.Count);
  }
  void WriteListEnd() override {}

  void WriteSetBegin(const DpSet& set) override {
    WriteTag(PackTag::Array);
    WriteRawI32(set.Count);
  }
  void WriteSetEnd() override {}

  void WriteBool(bool value) override {
    WriteTag(value ? PackTag::True : PackTag::False);
  }

  void WriteByte(uint8 value) override {
    WriteTag(PackTag::Int32);
    WriteRawI32(value);
  }

  void WriteI16(int16 value) override {
    WriteTag(PackTag::Int32);
    WriteRawI32(value);
  }

  void WriteI32(int32 value) override {
    WriteTag(PackTag::Int32);
    WriteRawI32(value);
  }

  void WriteI64(int64 value) override {
    WriteTag(PackTag::Int64);
    WriteRawI64(value);
  }

  void WriteDouble(float64 value) override {
    WriteTag(PackTag::Double);
    WriteRawDouble(value);
  }

  void WriteString(const std::string& value) override {
    WriteTag(PackTag::String);
    WriteRawString(value);
  }

  void WriteBinary(const std::string& value) override {
    WriteTag(PackTag::Binary);
    WriteRawString(value);
  }

  private:
  void WriteRawString(const std::string& v) {
    WriteRawI32(static_cast<int32>(v.length()));
    if (output) output->write(v.data(), v.length());
  }

  void WriteRawI32(int32 v) {
    if (!output) return;
    output->put(static_cast<char>(v & 0xFF));
    output->put(static_cast<char>((v >> 8) & 0xFF));
    output->put(static_cast<char>((v >> 16) & 0xFF));
    output->put(static_cast<char>((v >> 24) & 0xFF));
  }

  void WriteRawI64(int64 v) {
    if (!output) return;
    for (int i = 0; i < 8; ++i) {
        output->put(static_cast<char>(v & 0xFF));
        v >>= 8;
    }
  }

  void WriteRawDouble(float64 v) {
    union { float64 d; int64 i; } u;
    u.d = v;
    WriteRawI64(u.i);
  }

  uint8 ReadRawByte() {
    if (!input) return 0;
    int c = input->get();
    if (c == EOF) return 0;
    return static_cast<uint8>(c);
  }

  int32 ReadRawI32() {
    uint32 b1 = ReadRawByte();
    uint32 b2 = ReadRawByte();
    uint32 b3 = ReadRawByte();
    uint32 b4 = ReadRawByte();
    return static_cast<int32>(b1 | (b2 << 8) | (b3 << 16) | (b4 << 24));
  }

  int64 ReadRawI64() {
    uint64 v = 0;
    for (int i = 0; i < 8; ++i) {
        v |= (static_cast<uint64>(ReadRawByte()) << (8 * i));
    }
    return static_cast<int64>(v);
  }

  public:
  DpMessage ReadMessageBegin() override {
    PackTag tag = static_cast<PackTag>(ReadRawByte());
    if (tag != PackTag::Array) throw std::runtime_error("Expected Array tag");
    ReadRawI32(); // count
    return {ReadString(), static_cast<DpMessageType>(ReadByte()), ReadI32()};
  }
  void ReadMessageEnd() override {}

  DpRecord ReadStructBegin() override {
    PackTag tag = static_cast<PackTag>(ReadRawByte());
    if (tag != PackTag::Object) throw std::runtime_error("Expected Object tag");
    int32 count = ReadRawI32();
    fieldCounts.push(count);
    return {};
  }
  void ReadStructEnd() override {}

  DpColumn ReadFieldBegin() override {
    if (fieldCounts.empty()) return {"", DpWireType::Stop, 0};
    int32& count = fieldCounts.top();
    if (count <= 0) {
      fieldCounts.pop();
      return {"", DpWireType::Stop, 0};
    }
    count--;
    return {ReadRawString(), DpWireType::Void, 0};
  }
  void ReadFieldEnd() override {}

  private:
  std::string ReadRawString() {
    int32 len = ReadRawI32();
    if (len <= 0) return {};
    std::string s(len, '\0');
    if (input) input->read(&s[0], len);
    return s;
  }

  public:
  DpDict ReadMapBegin() override {
    if (static_cast<PackTag>(ReadRawByte()) != PackTag::Map) throw std::runtime_error("Expected Map tag");
    return {DpWireType::Stop, DpWireType::Stop, ReadRawI32()};
  }
  void ReadMapEnd() override {}

  DpList ReadListBegin() override {
    if (static_cast<PackTag>(ReadRawByte()) != PackTag::Array) throw std::runtime_error("Expected Array tag");
    return {DpWireType::Stop, ReadRawI32()};
  }
  void ReadListEnd() override {}

  DpSet ReadSetBegin() override {
    if (static_cast<PackTag>(ReadRawByte()) != PackTag::Array) throw std::runtime_error("Expected Array tag");
    return {DpWireType::Stop, ReadRawI32()};
  }
  void ReadSetEnd() override {}

  bool ReadBool() override {
    PackTag tag = static_cast<PackTag>(ReadRawByte());
    return tag == PackTag::True;
  }

  uint8 ReadByte() override {
    return static_cast<uint8>(ReadI32());
  }

  int16 ReadI16() override {
    return static_cast<int16>(ReadI32());
  }

  int32 ReadI32() override {
    PackTag tag = static_cast<PackTag>(ReadRawByte());
    if (tag == PackTag::Int32) return ReadRawI32();
    if (tag == PackTag::Int64) return static_cast<int32>(ReadRawI64());
    throw std::runtime_error("Expected Int tag");
  }

  int64 ReadI64() override {
    PackTag tag = static_cast<PackTag>(ReadRawByte());
    if (tag == PackTag::Int32) return static_cast<int64>(ReadRawI32());
    if (tag == PackTag::Int64) return ReadRawI64();
    throw std::runtime_error("Expected Int tag");
  }

  float64 ReadDouble() override {
    PackTag tag = static_cast<PackTag>(ReadRawByte());
    if (tag == PackTag::Double) {
      union { float64 d; int64 i; } u;
      u.i = ReadRawI64();
      return u.d;
    }
    if (tag == PackTag::Int32) return static_cast<float64>(ReadRawI32());
    throw std::runtime_error("Expected Double tag");
  }

  std::string ReadString() override {
    PackTag tag = static_cast<PackTag>(ReadRawByte());
    if (tag == PackTag::Null) return "";
    if (tag != PackTag::String) throw std::runtime_error("Expected String tag");
    return ReadRawString();
  }

  std::string ReadBinary() override {
    PackTag tag = static_cast<PackTag>(ReadRawByte());
    if (tag == PackTag::Null) return "";
    if (tag != PackTag::Binary) throw std::runtime_error("Expected Binary tag");
    return ReadRawString();
  }
};

} // namespace deuk
