/**
 * Autogenerated by DeukPack v1.4.0
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * @generated
 */
#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <map>
#include <set>
#include <any>
#include <unordered_map>
#include "DpProtocol.h"

#include "DpProtocol.h"
#include <memory>
#include <vector>
#include <map>
#include <set>

namespace deuk {
namespace test {

  enum class TestEnum {
    Alpha = 1,
    Beta = 2,
    Gamma = 3
  };

  struct RoundtripModel;
  struct NestedStruct;
  struct EnumModel;


struct RoundtripModel : public deuk::IDpSerializable {
  std::shared_ptr<bool> b_val;
  std::shared_ptr<deuk::int8> i8_val;
  std::shared_ptr<deuk::int16> i16_val;
  std::shared_ptr<deuk::int32> i32_val;
  std::shared_ptr<deuk::int64> i64_val;
  std::shared_ptr<deuk::float32> f_val;
  std::shared_ptr<deuk::float64> d_val;
  std::shared_ptr<std::string> s_val;
  std::shared_ptr<std::string> bin_val;
  std::shared_ptr<std::vector<deuk::int32>> i32_list;
  std::shared_ptr<std::vector<std::string>> s_list;
  std::shared_ptr<std::map<std::string, deuk::int32>> s_i32_map;
  std::shared_ptr<NestedStruct> nested;

  static constexpr int kFieldId_B_val = 1;
  static constexpr int kFieldId_I8_val = 2;
  static constexpr int kFieldId_I16_val = 3;
  static constexpr int kFieldId_I32_val = 4;
  static constexpr int kFieldId_I64_val = 5;
  static constexpr int kFieldId_F_val = 6;
  static constexpr int kFieldId_D_val = 7;
  static constexpr int kFieldId_S_val = 8;
  static constexpr int kFieldId_Bin_val = 9;
  static constexpr int kFieldId_I32_list = 10;
  static constexpr int kFieldId_S_list = 11;
  static constexpr int kFieldId_S_i32_map = 12;
  static constexpr int kFieldId_Nested = 13;

  void Write(deuk::DpProtocol& oprot) const override;
  void Read(deuk::DpProtocol& iprot) override;
};


struct NestedStruct : public deuk::IDpSerializable {
  std::shared_ptr<std::string> inner_val;
  std::shared_ptr<std::vector<deuk::int32>> numbers;

  static constexpr int kFieldId_Inner_val = 1;
  static constexpr int kFieldId_Numbers = 2;

  void Write(deuk::DpProtocol& oprot) const override;
  void Read(deuk::DpProtocol& iprot) override;
};


struct EnumModel : public deuk::IDpSerializable {
  std::shared_ptr<TestEnum> e_val;

  static constexpr int kFieldId_E_val = 1;

  void Write(deuk::DpProtocol& oprot) const override;
  void Read(deuk::DpProtocol& iprot) override;
};

} // namespace test
} // namespace deuk
