// Autogenerated by DeukPack — wire profile "@@PROFILE_ESCAPED@@" subset types.
// Field filter: annotation ( wireProfiles = "…" ) on each field; omitted = all profiles.
// @generated
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Runtime.Serialization;
using System.Linq;
using DeukPack.Protocol;

