// Autogenerated by DeukPack (EF support). DbContext for meta tables (partial — extend in your own .cs).
// Optional: implement partial void OnModelCreatingPartial(ModelBuilder) for extra fluent config.
// Add Microsoft.EntityFrameworkCore + provider (e.g. Sqlite) to your project.
// @generated
using System;
using Microsoft.EntityFrameworkCore;

namespace Generated
{
  public partial class DeukPackDbContext : DbContext
  {
    public DeukPackDbContext(DbContextOptions<DeukPackDbContext> options) : base(options) { }

@@DBSET_PROPERTIES@@

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
@@ONMODEL_BODY@@
      OnModelCreatingPartial(modelBuilder);
    }
  }
}
