// Autogenerated by DeukPack — geometry record from IDL (`geometry` annotation).
// @generated
// Layout from IDL only. Vector ops and Unity implicits: hand-maintained `deuk_geometry.impl.cs` partial next to this file.

  [System.Serializable]
  [System.Runtime.InteropServices.StructLayout(System.Runtime.InteropServices.LayoutKind.Sequential)]
  public partial struct @@STRUCT_NAME@@ : System.IEquatable<@@STRUCT_NAME@@>
  {
@@MEMBERS@@
  }
