// Autogenerated by DeukPack. Meta table registry — use instead of reflection for container/row type lookup and empty template.
// When using table/container, ensure TableHeader and TableInfos types are available (e.g. include deuk.deuk or shared IDL).
// @generated
using System;
using DeukPack.Protocol;

namespace Generated
{
  public static class MetaTableRegistry
  {
    // include 포함 전체 스키마(구조/와이어 영향)의 지문. 정의 변경 시 값이 바뀌어 스키마 버전 변경 여부 판단에 사용.
    public static readonly string SchemaFingerprint = "@@FINGERPRINT@@";

    public static Type GetContainerType(string category)
    {
      if (category == null) return null;
      switch (category)
      {
@@SWITCH_GETCONTAINER@@
        default: return null;
      }
    }

    public static Type GetRowType(string category)
    {
      if (category == null) return null;
      switch (category)
      {
@@SWITCH_GETROW@@
        default: return null;
      }
    }

    // 카테고리별 키 필드명(단일 또는 복합). key 미선언 시 ["tuid"]. 매니저 검색·엑셀 칼럼 순서·보조 인덱스 판단용.
    public static System.Collections.Generic.IReadOnlyList<string> GetKeyFieldNames(string category)
    {
      if (category == null) return null;
      switch (category)
      {
@@SWITCH_GETKEYS@@
        default: return null;
      }
    }

    // 카테고리별 빈 메타 테이블 템플릿 생성 (Default_Header + 빈 Infos). 로더/툴에서 초기 컨테이너가 필요할 때 사용.
    public static IDeukMetaContainer CreateEmptyTemplate(string category)
    {
      if (category == null) return null;
      switch (category)
      {
@@SWITCH_CREATEEMPTY@@
        default: return null;
      }
    }
  }
}

