// Generated by DeukPack v1.4.0 | https://deukpack.app
// Powered by DeukPack — Universal IDL Gateway for AI & Unity
// 2026-03-29T12:41:41.407Z
// JS build pipeline: Path B (direct JS). See DeukPack docs/DEUKPACK_JS_BUILD_PIPELINE.md
// DeukPack JS objects with embedded schema (getSchema(), toJson/fromJson). Consumer-agnostic.
// Protocol helpers: toJson/fromJson (DeukPack JSON), toBinary/fromBinary (binary).
// DeukPack JSON wire uses fixed wrapper keys (i32, str, lst, …) for consumer compatibility; see docs/DEUKPACK_JS_BUILD_PIPELINE.md §2.

// --- Protocol runtime: DeukPack JSON on the wire (compatibility protocol; do not rename keys) ---
// Field IDs are object keys. Each value is a tagged wrapper: { i32 }, { i64 }, { str }, { lst }, { map }, { rec }, { tf }, { dbl }, …
// Wrapper property names (i32, str, …) are FIXED wire vocabulary — not schema spellings.
// getSchema().fields[].type / typeName: **DeukPack IDL tokens** (int32, bool, list<…>, struct, enum, …) — not Thrift-style I32/Bool.
function _deukSerializationWarn(kind, structName, fieldNameOrId, fieldId) {
  try {
    if (typeof console !== 'undefined' && console.warn) {
      var msg = kind === 'unknown' ? 'Unknown field' : 'Missing required field';
      console.warn('[DeukPack] ' + msg + ': struct=' + structName + (fieldNameOrId != null ? ', field=' + fieldNameOrId : '') + (fieldId != null ? ', fieldId=' + fieldId : ''));
    }
  } catch (e) {}
}
function _wrapDpJson(type, typeName, val, schemas) {
  if (val === null || val === undefined) return null;
  switch (type) {
    case "bool": return { tf: !!val };
    case "int8":
    case "byte":
    case "int16":
    case "int32":
    case "date":
    case "time":
      return { i32: Number(val) };
    case "int64":
    case "datetime":
    case "timestamp":
    case "tablelink":
      return { i64: Number(val) };
    case "float":
    case "double":
      return { dbl: Number(val) };
    case "enum":
      return { i32: Number(val) };
    case "string":
      return { str: String(val) };
    case "binary":
      if (typeof Buffer !== "undefined") return { str: Buffer.from(val).toString("base64") };
      var arr = val && val.length != null ? val : []; var s = ""; for (var i = 0; i < arr.length; i++) s += String.fromCharCode(arr[i] & 255); return { str: (typeof btoa !== "undefined" ? btoa(s) : "") };
    case "decimal":
    case "numeric":
      return { str: String(val) };
    case "list":
    case "set":
      var elem = (typeName.match(/^(?:list|set)<(.+)>$/i) || [])[1];
      elem = elem ? elem.trim() : "";
      return { lst: (val || []).map(function(e) { return _wrapDpJson(_elemType(elem), elem, e, schemas); }) };
    case "map":
      var m = (typeName.match(/^map<([^,]+),(.+)>$/i) || []);
      var out = {};
      for (var k in val) if (Object.prototype.hasOwnProperty.call(val, k)) { var mv = m[2] ? m[2].trim() : ""; out[String(k)] = _wrapDpJson(_elemType(mv), mv, val[k], schemas); }
      return { map: out };
    default:
      var s = schemas && schemas[typeName];
      return s ? { rec: _toDpJson(s, val, schemas) } : { str: String(val) };
  }
}
function _elemType(tn) {
  if (!tn) return "string";
  var raw = String(tn).trim();
  var m = raw.match(/^(?:list|set)<(.+)>$/i);
  if (m) return _elemType(m[1].trim());
  if (/^tablelink\s*</i.test(raw)) return "int64";
  var x = raw.toLowerCase();
  if (x === "bool" || x === "tf") return "bool";
  if (x === "byte" || x === "int8" || x === "i8") return "int8";
  if (x === "int16" || x === "i16") return "int16";
  if (x === "int32" || x === "i32") return "int32";
  if (x === "int64" || x === "i64") return "int64";
  if (x === "double" || x === "dbl") return "double";
  if (x === "float") return "float";
  if (x === "string" || x === "str") return "string";
  if (x === "binary") return "binary";
  if (x === "datetime") return "datetime";
  if (x === "timestamp") return "timestamp";
  if (x === "date") return "date";
  if (x === "time") return "time";
  if (x === "decimal") return "decimal";
  if (x === "numeric") return "numeric";
  return "struct";
}
function _toDpJson(schema, obj, schemas) {
  if (!schema || (schema.type !== "struct" && schema.type !== "Struct") || !schema.fields) return obj;
  var out = {};
  for (var id in schema.fields) { var f = schema.fields[id]; var v = obj && obj[f.name]; if (v === undefined && f.defaultValue !== undefined && f.defaultValue !== null) v = f.defaultValue; if (v !== undefined) out[String(id)] = _wrapDpJson(f.type, f.typeName, v, schemas); }
  return out;
}
function _toDpJsonFiltered(schema, obj, schemas, fieldIds, overrides) {
  if (!schema || (schema.type !== "struct" && schema.type !== "Struct") || !schema.fields) return obj;
  var idSet = fieldIds ? {} : null;
  if (fieldIds) { for (var i = 0; i < fieldIds.length; i++) idSet[fieldIds[i]] = true; }
  var out = {};
  for (var id in schema.fields) {
    if (idSet && !idSet[id]) continue;
    var f = schema.fields[id];
    var v = (overrides && overrides[id] !== undefined) ? overrides[id] : (obj && obj[f.name]);
    if (v === undefined && f.defaultValue !== undefined && f.defaultValue !== null) v = f.defaultValue;
    if (v !== undefined) out[String(id)] = _wrapDpJson(f.type, f.typeName, v, schemas);
  }
  return out;
}
// Unwrap: reads wire keys (.i32, .str, …) from the compatibility JSON shape above.
function _unwrapDpJson(type, typeName, jsonVal, schemas) {
  if (jsonVal === null || jsonVal === undefined) return null;
  if (typeof jsonVal === "object" && !Array.isArray(jsonVal) && jsonVal.rec !== undefined) {
    var sn = schemas && schemas[typeName];
    if (sn && (type === "struct" || type === "Struct")) return _fromDpJson(sn, jsonVal.rec, schemas);
  }
  if (type === "struct" || type === "Struct") return jsonVal;
  if (typeof jsonVal === "object" && !Array.isArray(jsonVal)) {
    if (type === "binary" && jsonVal.str) { var b64 = jsonVal.str; if (typeof Buffer !== "undefined") return new Uint8Array(Buffer.from(b64, "base64")); var bin = typeof atob !== "undefined" ? atob(b64) : ""; var arr = new Uint8Array(bin.length); for (var i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i); return arr; }
    if (jsonVal.str !== undefined) return jsonVal.str;
    if (jsonVal.i32 !== undefined) return jsonVal.i32;
    if (jsonVal.i64 !== undefined) return Number(jsonVal.i64);
    if (jsonVal.dbl !== undefined) return jsonVal.dbl;
    if (jsonVal.tf !== undefined) return jsonVal.tf;
    if (jsonVal.lst !== undefined) { var elem = (typeName.match(/^(?:list|set)<(.+)>$/i) || [])[1]; elem = elem ? elem.trim() : ""; return jsonVal.lst.map(function(e) { return _unwrapDpJson(_elemType(elem), elem, e, schemas); }); }
    if (jsonVal.map !== undefined) { var mm = (typeName.match(/^map<([^,]+),(.+)>$/i) || []); var vt = mm[2] ? mm[2].trim() : ""; var o = {}; for (var k in jsonVal.map) o[k] = _unwrapDpJson(_elemType(vt), vt, jsonVal.map[k], schemas); return o; }
    if (jsonVal.rec !== undefined) { var s = schemas && schemas[typeName]; return s ? _fromDpJson(s, jsonVal.rec, schemas) : jsonVal.rec; }
  }
  return jsonVal;
}
function _fromDpJson(schema, jsonObj, schemas) {
  if (!schema || (schema.type !== "struct" && schema.type !== "Struct") || !schema.fields) return jsonObj || {};
  var structName = (schema && schema.name) ? schema.name : 'Struct';
  if (jsonObj && typeof jsonObj === 'object') {
    for (var k in jsonObj) { if (Object.prototype.hasOwnProperty.call(jsonObj, k) && !schema.fields[k]) _deukSerializationWarn('unknown', structName, k, k); }
  }
  var out = {};
  for (var id in schema.fields) {
    var f = schema.fields[id];
    var w = jsonObj && jsonObj[String(id)];
    if (f.required && w === undefined) _deukSerializationWarn('missing', structName, f.name, id);
    if (w !== undefined) out[f.name] = _unwrapDpJson(f.type, f.typeName, w, schemas);
  }
  return out;
}

// Excel row constants: Row 1=HIERARCHY_ID, Row 2=DATATYPE, Row 5+=DATA
var _XL_HIER_ROW = 1, _XL_DT_ROW = 2, _XL_FIRST_DATA = 5;
function _xlBuildColMap(sheet) {
  var m = {}; for (var c = 1; c <= sheet.lastColumn; c++) { var h = (sheet.cellValue(_XL_HIER_ROW, c) || "").trim(); if (!h) break; m[h] = { col: c, dt: (sheet.cellValue(_XL_DT_ROW, c) || "").trim() }; } return m;
}
function _xlParsePrimitive(type, raw, dt, enums) {
  if (raw === null || raw === undefined || raw === "") return type === "string" ? "" : undefined;
  var tok = String(raw).split(":")[0].trim();
  switch (type) {
    case "bool": return tok === "1" || tok.toLowerCase() === "true";
    case "int8":
    case "byte":
    case "int16":
    case "int32":
    case "date":
    case "time":
      var n = parseInt(tok, 10); if (!isNaN(n)) return n;
      if (enums && dt && dt.indexOf("enum") === 0) { var en = dt.replace(/^enum[<(]|[>)]$/g,""); var ed = enums[en]; if (ed && ed.values && ed.values[tok] !== undefined) return ed.values[tok]; }
      return 0;
    case "int64":
    case "datetime":
    case "timestamp":
    case "tablelink":
      return parseInt(tok, 10) || 0;
    case "float":
    case "double":
      return parseFloat(raw) || 0;
    case "string":
    case "decimal":
    case "numeric":
      return String(raw).trim();
    default: return String(raw).trim();
  }
}
function _xlMapType(tn) {
  var x = String(tn || "").trim().toLowerCase();
  var m = { i32:"int32", int32:"int32", i64:"int64", int64:"int64", i16:"int16", int16:"int16", i8:"int8", int8:"int8", byte:"byte", double:"double", float:"float", dbl:"double", string:"string", str:"string", bool:"bool", tf:"bool", binary:"binary", datetime:"datetime", timestamp:"timestamp", date:"date", time:"time", decimal:"decimal", numeric:"numeric" };
  return m[x] || "struct";
}
function _xlCountListRows(sheet, row, listPath, colMap) {
  var tuid = sheet.cellValue(row, 1) || "", pfx = listPath + ".", cnt = 0;
  for (var r = row; r <= sheet.lastRow; r++) {
    if (r > row) { var rid = sheet.cellValue(r, 1) || ""; if (rid && rid !== tuid) break; }
    var has = false; for (var p in colMap) { if ((p === listPath || p.indexOf(pfx) === 0) && !sheet.isCellEmpty(r, colMap[p].col)) { has = true; break; } }
    if (has) cnt++; else if (cnt > 0) break;
  } return cnt;
}
function _xlReadField(field, fid, colMap, sheet, row, schemas, enums, parentPath) {
  var fp = parentPath ? parentPath + "." + fid : String(fid);
  var type = field.type, tn = field.typeName;
  if (type === "struct" || type === "Struct") {
    var cs = schemas[tn]; if (!cs || !cs.fields) return undefined;
    var obj = {}, has = false;
    for (var cid in cs.fields) { var cf = cs.fields[cid]; var v = _xlReadField(cf, cid, colMap, sheet, row, schemas, enums, fp); if (v !== undefined && v !== null) { obj[cf.name] = v; has = true; } }
    return has ? obj : undefined;
  }
  if (type === "list" || type === "set" || type === "List" || type === "Set") {
    var cnt = _xlCountListRows(sheet, row, fp, colMap); if (cnt === 0) return undefined;
    var em = (tn.match(/^(?:list|set)<(.+)>$/i) || [])[1] || "struct";
    em = em ? em.trim().toLowerCase() : "struct";
    var isPrim = ["i32","int32","i64","int64","i16","int16","i8","int8","double","float","string","bool","byte","dbl","str","tf","binary","date","time","datetime","timestamp","decimal","numeric","tablelink"].indexOf(em) >= 0;
    var arr = [], pfx = fp + ".";
    for (var i = 0; i < cnt; i++) { var er = row + i;
      if (isPrim) { for (var p in colMap) { if (p.indexOf(pfx) === 0) { arr.push(_xlParsePrimitive(_xlMapType(em), sheet.cellValue(er, colMap[p].col), colMap[p].dt, enums)); break; } } }
      else { var es = schemas[em], eo = {};
        if (es && es.fields) { for (var cid in es.fields) { var cf = es.fields[cid]; var v = _xlReadField(cf, cid, colMap, sheet, er, schemas, enums, fp); if (v !== undefined && v !== null) eo[cf.name] = v; } }
        else { for (var p in colMap) { if (p.indexOf(pfx) === 0) { var rem = p.substring(pfx.length); if (rem.indexOf(".") < 0 && !sheet.isCellEmpty(er, colMap[p].col)) eo[rem] = sheet.cellValue(er, colMap[p].col); } } }
        arr.push(eo);
      }
    } return arr.length > 0 ? arr : undefined;
  }
  var e = colMap[fp]; if (!e) return undefined;
  if (sheet.isCellEmpty(row, e.col)) return undefined;
  return _xlParsePrimitive(type, sheet.cellValue(row, e.col), e.dt, enums);
}
function _fromExcelRow(schema, sheet, row, schemas, enums) {
  if (!schema || (schema.type !== "struct" && schema.type !== "Struct") || !schema.fields) return {};
  var colMap = _xlBuildColMap(sheet), out = {};
  for (var fid in schema.fields) { var f = schema.fields[fid]; var v = _xlReadField(f, fid, colMap, sheet, row, schemas, enums); if (v !== undefined && v !== null) out[f.name] = v; }
  return out;
}
function _fromExcelSheet(schema, sheet, schemas, enums, firstRow) {
  firstRow = firstRow || _XL_FIRST_DATA; var result = {};
  for (var r = firstRow; r <= sheet.lastRow; r++) { var tuid = sheet.cellValue(r, 1); if (!tuid) continue; var id = parseInt(String(tuid).split(":")[0], 10); if (isNaN(id)) continue; result[id] = _fromExcelRow(schema, sheet, r, schemas, enums); }
  return result;
}
// --- Deuk native `pack` wire (WireSerializer / WireDeserializer parity, LE) ---
var _PackTag = { Null: 0, False: 1, True: 2, Int32: 3, Int64: 4, Double: 5, String: 6, Binary: 7, Array: 8, Map: 9, Object: 10 };
function _packPushI32(a, v) {
  v = v | 0;
  a.push(v & 255, (v >> 8) & 255, (v >> 16) & 255, (v >> 24) & 255);
}
function _packPushStringBytes(a, s) {
  var enc = typeof TextEncoder !== "undefined" ? new TextEncoder().encode(s) : null;
  var bytes;
  if (enc) bytes = enc;
  else {
    bytes = [];
    for (var i = 0; i < s.length; i++) {
      var c = s.charCodeAt(i);
      if (c < 128) bytes.push(c);
      else bytes.push(63);
    }
  }
  _packPushI32(a, bytes.length);
  for (var j = 0; j < bytes.length; j++) a.push(bytes[j] & 255);
}
function _packPushDouble(a, d) {
  var u8 = new Uint8Array(8);
  new DataView(u8.buffer).setFloat64(0, Number(d), true);
  for (var i = 0; i < 8; i++) a.push(u8[i]);
}
function _packPushI64(a, n) {
  var u8 = new Uint8Array(8);
  var dv = new DataView(u8.buffer);
  if (typeof dv.setBigInt64 === "function") {
    dv.setBigInt64(0, BigInt(Math.trunc(Number(n))), true);
  } else {
    var v = Math.trunc(Number(n));
    var lo = v >>> 0;
    var hi = Math.floor(v / 4294967296);
    dv.setUint32(0, lo, true);
    dv.setInt32(4, hi, true);
  }
  for (var i = 0; i < 8; i++) a.push(u8[i]);
}
function _packWriteNumber(a, n) {
  if (!isFinite(n)) {
    a.push(_PackTag.Double);
    _packPushDouble(a, n);
    return;
  }
  var t = Math.trunc(Number(n));
  if (t === n && t >= -2147483648 && t <= 2147483647) {
    a.push(_PackTag.Int32);
    _packPushI32(a, t);
    return;
  }
  if (t === n) {
    a.push(_PackTag.Int64);
    _packPushI64(a, t);
    return;
  }
  a.push(_PackTag.Double);
  _packPushDouble(a, n);
}
function _packWriteValue(a, val, f, schemas) {
  if (val === null || val === undefined) {
    a.push(_PackTag.Null);
    return;
  }
  var t = f ? f.type : "";
  var tn = f ? f.typeName : "";
  if (t === "enum") {
    a.push(_PackTag.Int32);
    _packPushI32(a, val | 0);
    return;
  }
  if (t === "bool") {
    a.push(val ? _PackTag.True : _PackTag.False);
    return;
  }
  if (t === "int8" || t === "byte" || t === "int16" || t === "int32" || t === "date" || t === "time") {
    a.push(_PackTag.Int32);
    _packPushI32(a, val | 0);
    return;
  }
  if (t === "int64" || t === "datetime" || t === "timestamp" || t === "tablelink") {
    a.push(_PackTag.Int64);
    _packPushI64(a, val);
    return;
  }
  if (t === "float" || t === "double") {
    a.push(_PackTag.Double);
    _packPushDouble(a, Number(val));
    return;
  }
  if (t === "string" || t === "decimal" || t === "numeric") {
    a.push(_PackTag.String);
    _packPushStringBytes(a, String(val));
    return;
  }
  if (t === "binary") {
    a.push(_PackTag.Binary);
    var u8 = val && val.buffer ? new Uint8Array(val.buffer, val.byteOffset, val.byteLength) : new Uint8Array(val || []);
    _packPushI32(a, u8.length);
    for (var i = 0; i < u8.length; i++) a.push(u8[i] & 255);
    return;
  }
  if (t === "struct") {
    var cs = schemas && schemas[tn];
    if (!cs) throw new Error("[DeukPack] pack: unknown struct " + tn);
    _packWriteStructBody(a, cs, val, schemas);
    return;
  }
  if (t === "list" || t === "set") {
    var em = (tn.match(/^(?:list|set)<(.+)>$/i) || [])[1];
    em = em ? em.trim() : "";
    var arr = val || [];
    a.push(_PackTag.Array);
    _packPushI32(a, arr.length);
    var fake = { type: _packElemWireType(em), typeName: em, required: true };
    for (var j = 0; j < arr.length; j++) _packWriteValue(a, arr[j], fake, schemas);
    return;
  }
  if (t === "map") {
    var mm = (tn.match(/^map<([^,]+),(.+)>$/i) || []);
    var kt = mm[1] ? mm[1].trim() : "string";
    var vt = mm[2] ? mm[2].trim() : "string";
    var entries = val instanceof Map ? Array.from(val.entries()) : Object.keys(val || {}).map(function (k) { return [k, val[k]]; });
    a.push(_PackTag.Map);
    _packPushI32(a, entries.length);
    var fk = { type: _packElemWireType(kt), typeName: kt, required: true };
    var fv = { type: _packElemWireType(vt), typeName: vt, required: true };
    for (var e = 0; e < entries.length; e++) {
      _packWriteValue(a, entries[e][0], fk, schemas);
      _packWriteValue(a, entries[e][1], fv, schemas);
    }
    return;
  }
  if (typeof val === "boolean") {
    a.push(val ? _PackTag.True : _PackTag.False);
    return;
  }
  if (typeof val === "number") {
    _packWriteNumber(a, val);
    return;
  }
  if (typeof val === "string") {
    a.push(_PackTag.String);
    _packPushStringBytes(a, val);
    return;
  }
  if (val && val.buffer && val.byteLength !== undefined) {
    a.push(_PackTag.Binary);
    var b = new Uint8Array(val.buffer, val.byteOffset, val.byteLength);
    _packPushI32(a, b.length);
    for (var x = 0; x < b.length; x++) a.push(b[x] & 255);
    return;
  }
  if (Array.isArray(val)) {
    a.push(_PackTag.Array);
    _packPushI32(a, val.length);
    for (var y = 0; y < val.length; y++) _packWriteValue(a, val[y], null, schemas);
    return;
  }
  if (val instanceof Map) {
    a.push(_PackTag.Map);
    _packPushI32(a, val.size);
    val.forEach(function (vv, kk) {
      _packWriteValue(a, kk, null, schemas);
      _packWriteValue(a, vv, null, schemas);
    });
    return;
  }
  if (typeof val === "object") {
    a.push(_PackTag.Object);
    var keys = Object.keys(val);
    _packPushI32(a, keys.length);
    for (var z = 0; z < keys.length; z++) {
      _packPushStringBytes(a, keys[z]);
      _packWriteValue(a, val[keys[z]], null, schemas);
    }
    return;
  }
  a.push(_PackTag.Null);
}
function _packElemWireType(em) {
  var x = String(em || "").trim().toLowerCase();
  if (x === "bool" || x === "tf") return "bool";
  if (x === "byte" || x === "int8" || x === "i8") return "int8";
  if (x === "int16" || x === "i16") return "int16";
  if (x === "int32" || x === "i32") return "int32";
  if (x === "int64" || x === "i64") return "int64";
  if (x === "float") return "float";
  if (x === "double" || x === "dbl") return "double";
  if (x === "string" || x === "str") return "string";
  if (x === "binary") return "binary";
  if (x === "datetime") return "datetime";
  if (x === "timestamp") return "timestamp";
  if (x === "date") return "date";
  if (x === "time") return "time";
  if (x === "decimal") return "decimal";
  if (x === "numeric") return "numeric";
  if (/^tablelink\s*</i.test(String(em || ""))) return "tablelink";
  return "struct";
}
function _packWriteStructBody(a, schema, obj, schemas) {
  if (!schema || (schema.type !== "struct" && schema.type !== "Struct") || !schema.fields) throw new Error("[DeukPack] pack: invalid struct schema");
  a.push(_PackTag.Object);
  var ids = Object.keys(schema.fields)
    .map(function (k) { return parseInt(k, 10); })
    .filter(function (x) { return !isNaN(x); })
    .sort(function (p, q) { return p - q; });
  var parts = [];
  for (var i = 0; i < ids.length; i++) {
    var id = ids[i];
    var f = schema.fields[id];
    var v = obj && obj[f.name];
    if (v === undefined && f.defaultValue !== undefined && f.defaultValue !== null) v = f.defaultValue;
    if (v === undefined || v === null) {
      if (f.required) _deukSerializationWarn("missing", schema.name || "Struct", f.name, id);
      continue;
    }
    parts.push(f.name, f, v);
  }
  _packPushI32(a, parts.length / 3);
  for (var j = 0; j < parts.length; j += 3) {
    _packPushStringBytes(a, parts[j]);
    _packWriteValue(a, parts[j + 2], parts[j + 1], schemas);
  }
}
function _packStructToBinary(schema, obj, schemas) {
  var a = [];
  _packWriteStructBody(a, schema, obj, schemas);
  return new Uint8Array(a);
}
function _structToPackBinaryFiltered(schema, obj, schemas, fieldIds, overrides) {
  var a = [];
  _packWriteStructBodyFiltered(a, schema, obj, schemas, fieldIds, overrides);
  return new Uint8Array(a);
}
function _packWriteStructBodyFiltered(a, schema, obj, schemas, fieldIds, overrides) {
  if (!schema || (schema.type !== "struct" && schema.type !== "Struct") || !schema.fields) throw new Error("[DeukPack] pack: invalid struct schema");
  var idSet = fieldIds ? {} : null;
  if (fieldIds) { for (var i = 0; i < fieldIds.length; i++) idSet[fieldIds[i]] = true; }
  a.push(_PackTag.Object);
  var ids = Object.keys(schema.fields)
    .map(function (k) { return parseInt(k, 10); })
    .filter(function (x) { return !isNaN(x); })
    .sort(function (p, q) { return p - q; });
  var parts = [];
  for (var i = 0; i < ids.length; i++) {
    var id = ids[i];
    if (idSet && !idSet[id]) continue;
    var f = schema.fields[id];
    var v = (overrides && overrides[id] !== undefined) ? overrides[id] : (obj && obj[f.name]);
    if (v === undefined && f.defaultValue !== undefined && f.defaultValue !== null) v = f.defaultValue;
    if (v === undefined || v === null) {
      if (f.required) _deukSerializationWarn("missing", schema.name || "Struct", f.name, id);
      continue;
    }
    parts.push(f.name, f, v);
  }
  _packPushI32(a, parts.length / 3);
  for (var j = 0; j < parts.length; j += 3) {
    _packPushStringBytes(a, parts[j]);
    _packWriteValue(a, parts[j + 2], parts[j + 1], schemas);
  }
}
function _prU8(r) {
  if (r.i >= r.u8.length) throw new Error("[DeukPack] pack read overflow");
  return r.u8[r.i++];
}
function _prI32(r) {
  var b0 = _prU8(r), b1 = _prU8(r), b2 = _prU8(r), b3 = _prU8(r);
  return (b0 | (b1 << 8) | (b2 << 16) | (b3 << 24)) >> 0;
}
function _prI64(r) {
  var dv = new DataView(r.u8.buffer, r.u8.byteOffset + r.i, 8);
  var lo = dv.getUint32(0, true);
  var hi = dv.getInt32(4, true);
  r.i += 8;
  return hi * 4294967296 + lo;
}
function _prDbl(r) {
  var d = new DataView(r.u8.buffer, r.u8.byteOffset + r.i, 8).getFloat64(0, true);
  r.i += 8;
  return d;
}
function _prString(r) {
  var len = _prI32(r);
  if (len < 0 || r.i + len > r.u8.length) throw new Error("[DeukPack] pack string len");
  var sl = r.u8.subarray(r.i, r.i + len);
  r.i += len;
  if (typeof TextDecoder !== "undefined") return new TextDecoder("utf-8", { fatal: true }).decode(sl);
  var s = "";
  for (var i = 0; i < sl.length; i++) s += String.fromCharCode(sl[i]);
  return s;
}
function _prBinary(r) {
  var len = _prI32(r);
  if (len < 0 || r.i + len > r.u8.length) throw new Error("[DeukPack] pack binary len");
  var out = r.u8.slice(r.i, r.i + len);
  r.i += len;
  return out;
}
function _packReadValue(r, f, schemas) {
  var tag = _prU8(r);
  if (tag === _PackTag.Null) return null;
  if (tag === _PackTag.False) return false;
  if (tag === _PackTag.True) return true;
  if (tag === _PackTag.Int32) return _prI32(r);
  if (tag === _PackTag.Int64) return _prI64(r);
  if (tag === _PackTag.Double) return _prDbl(r);
  if (tag === _PackTag.String) return _prString(r);
  if (tag === _PackTag.Binary) return _prBinary(r);
  if (tag === _PackTag.Array) {
    var n = _prI32(r);
    var em = f && f.typeName ? (f.typeName.match(/^(?:list|set)<(.+)>$/i) || [])[1] : "";
    em = em ? em.trim() : "";
    var fake = em ? { type: _packElemWireType(em), typeName: em, required: true } : null;
    var arr = [];
    for (var i = 0; i < n; i++) arr.push(_packReadValue(r, fake, schemas));
    return arr;
  }
  if (tag === _PackTag.Map) {
    var m = _prI32(r);
    var mm = f && f.typeName ? (f.typeName.match(/^map<([^,]+),(.+)>$/i) || []) : [];
    var vt = mm[2] ? mm[2].trim() : "";
    var fv = vt ? { type: _packElemWireType(vt), typeName: vt, required: true } : null;
    var fk = mm[1] ? { type: _packElemWireType(mm[1].trim()), typeName: mm[1].trim(), required: true } : null;
    var o = {};
    for (var j = 0; j < m; j++) {
      var k = _packReadValue(r, fk, schemas);
      o[String(k)] = _packReadValue(r, fv, schemas);
    }
    return o;
  }
  if (tag === _PackTag.Object) {
    var cnt = _prI32(r);
    var o2 = {};
    for (var k = 0; k < cnt; k++) {
      var key = _prString(r);
      var subf = null;
      if (f && f.type === "struct" && schemas && schemas[f.typeName]) {
        var sch = schemas[f.typeName];
        for (var fid in sch.fields) if (sch.fields[fid].name === key) subf = sch.fields[fid];
      }
      o2[key] = _packReadValue(r, subf, schemas);
    }
    return o2;
  }
  throw new Error("[DeukPack] pack: unknown tag " + tag);
}
function _packBinaryToStruct(schema, buf, schemas) {
  var u8 = buf && buf.buffer ? new Uint8Array(buf.buffer, buf.byteOffset, buf.byteLength) : new Uint8Array(buf || []);
  var r = { u8: u8, i: 0 };
  if (!schema || (schema.type !== "struct" && schema.type !== "Struct") || !schema.fields) throw new Error("[DeukPack] pack: invalid struct schema");
  if (_prU8(r) !== _PackTag.Object) throw new Error("[DeukPack] pack: expected Object tag");
  var cnt = _prI32(r);
  var raw = {};
  for (var i = 0; i < cnt; i++) {
    var key = _prString(r);
    var subf = null;
    for (var fid in schema.fields) {
      if (schema.fields[fid].name === key) subf = schema.fields[fid];
    }
    raw[key] = _packReadValue(r, subf, schemas);
  }
  var out = {};
  for (var id in schema.fields) {
    var f = schema.fields[id];
    var v = raw[f.name];
    if (v === undefined && f.defaultValue !== undefined && f.defaultValue !== null) v = f.defaultValue;
    if (v === undefined && f.required) _deukSerializationWarn("missing", schema.name, f.name, id);
    if (v !== undefined) out[f.name] = v;
  }
  return out;
}
// --- DeukPack Binary Protocol for JS (Big Endian, Parity with C#/C++/Java) ---
function _jsBinPushI16(a, v) {
  a.push((v >> 8) & 255, v & 255);
}
function _jsBinPushI32(a, v) {
  a.push((v >> 24) & 255, (v >> 16) & 255, (v >> 8) & 255, v & 255);
}
function _jsBinPushI64(a, n) {
  var u8 = new Uint8Array(8);
  new DataView(u8.buffer).setBigInt64(0, BigInt(n), false); // Big Endian
  for (var i = 0; i < 8; i++) a.push(u8[i]);
}
function _jsBinPushDouble(a, d) {
  var u8 = new Uint8Array(8);
  new DataView(u8.buffer).setFloat64(0, Number(d), false);
  for (var i = 0; i < 8; i++) a.push(u8[i]);
}
function _jsBinWriteValue(a, val, type, typeName, schemas) {
  if (val === null || val === undefined) return;
  var wt = _toDpWireType(type);
  switch (wt) {
    case 2: a.push(val ? 1 : 0); break; // Bool
    case 3: a.push(val & 255); break; // Byte
    case 4: _jsBinPushDouble(a, val); break; // Double
    case 6: _jsBinPushI16(a, val); break; // Int16
    case 8: _jsBinPushI32(a, val); break; // Int32
    case 10: _jsBinPushI64(a, val); break; // Int64
    case 11: // String or Binary
      var bytes;
      if (val instanceof Uint8Array || (typeof Buffer !== "undefined" && Buffer.isBuffer(val))) {
        bytes = val;
      } else {
        bytes = typeof TextEncoder !== "undefined" ? new TextEncoder().encode(String(val)) : Buffer.from(String(val));
      }
      _jsBinPushI32(a, bytes.length);
      for (var i = 0; i < bytes.length; i++) a.push(bytes[i]);
      break;
    case 12: // Struct
      var s = schemas[typeName];
      _jsBinWriteStruct(a, s, val, schemas);
      break;
    case 13: // Map
      var mm = (typeName.match(/map<([^,]+),(.+)>/i) || []);
      var kt = mm[1] ? mm[1].trim() : "string";
      var vt = mm[2] ? mm[2].trim() : "string";
      var entries = val instanceof Map ? Array.from(val.entries()) : Object.keys(val || {}).map(function(k) { return [k, val[k]]; });
      a.push(_toDpWireType(_elemType(kt)));
      a.push(_toDpWireType(_elemType(vt)));
      _jsBinPushI32(a, entries.length);
      var ket = _elemType(kt);
      var vet = _elemType(vt);
      for (var e = 0; e < entries.length; e++) {
        _jsBinWriteValue(a, entries[e][0], ket, kt, schemas);
        _jsBinWriteValue(a, entries[e][1], vet, vt, schemas);
      }
      break;
    case 14: // Set
    case 15: // List
      var em = (typeName.match(/^(?:list|set)<(.+)>$/i) || [])[1] || "int32";
      var arr = Array.isArray(val) ? val : (val instanceof Set ? Array.from(val) : (val || []));
      a.push(_toDpWireType(_elemType(em)));
      _jsBinPushI32(a, arr.length);
      var eet = _elemType(em);
      for (var j = 0; j < arr.length; j++) _jsBinWriteValue(a, arr[j], eet, em, schemas);
      break;
  }
}
function _jsBinWriteStruct(a, schema, obj, schemas) {
  for (var id in schema.fields) {
    var f = schema.fields[id];
    var v = obj[f.name];
    if (v === undefined && f.defaultValue !== undefined) v = f.defaultValue;
    if (v !== undefined) {
      a.push(_toDpWireType(f.type));
      _jsBinPushI16(a, parseInt(id));
      _jsBinWriteValue(a, v, f.type, f.typeName, schemas);
    }
  }
  a.push(0); // Stop
}
function _jsBinReadI16(p) {
  var v = (p.view.getUint8(p.off) << 8) | p.view.getUint8(p.off + 1);
  p.off += 2;
  return v;
}
function _jsBinReadI32(p) {
  var v = p.view.getInt32(p.off, false);
  p.off += 4;
  return v;
}
function _jsBinReadDouble(p) {
  var v = p.view.getFloat64(p.off, false);
  p.off += 8;
  return v;
}
function _jsBinReadString(p) {
  var len = _jsBinReadI32(p);
  if (len === 0) return "";
  var s;
  if (typeof TextDecoder !== "undefined") {
    s = new TextDecoder().decode(new Uint8Array(p.view.buffer, p.view.byteOffset + p.off, len));
  } else {
    s = Buffer.from(p.view.buffer, p.view.byteOffset + p.off, len).toString();
  }
  p.off += len;
  return s;
}

function _jsBinSkip(p, wt) {
  switch (wt) {
    case 2: case 3: p.off += 1; break;
    case 6: p.off += 2; break;
    case 8: p.off += 4; break;
    case 4: case 10: p.off += 8; break;
    case 11: p.off += _jsBinReadI32(p); break;
    case 12: 
      while (true) {
        var swt = p.view.getUint8(p.off++);
        if (swt === 0) break;
        p.off += 2; // id
        _jsBinSkip(p, swt);
      }
      break;
    case 13: // Map
      var kt = p.view.getUint8(p.off++);
      var vt = p.view.getUint8(p.off++);
      var mc = _jsBinReadI32(p);
      for (var i = 0; i < mc; i++) { _jsBinSkip(p, kt); _jsBinSkip(p, vt); }
      break;
    case 14: // Set
    case 15: // List
      var et = p.view.getUint8(p.off++);
      var lc = _jsBinReadI32(p);
      for (var j = 0; j < lc; j++) _jsBinSkip(p, et);
      break;
  }
}

function _jsBinReadValue(p, type, typeName, schemas) {
  var wt = _toDpWireType(type);
  switch (wt) {
    case 2: return p.view.getUint8(p.off++) !== 0; // Bool
    case 3: return p.view.getUint8(p.off++); // Byte
    case 4: return _jsBinReadDouble(p);
    case 6: return _jsBinReadI16(p);
    case 8: return _jsBinReadI32(p);
    case 10: 
      var v = p.view.getBigInt64(p.off, false);
      p.off += 8;
      // Convert to Number for roundtrip verification if it fits
      return Number(v);
    case 11: // String or Binary
      if (type === "binary" || typeName === "binary") {
        var len = _jsBinReadI32(p);
        var buf = new Uint8Array(p.view.buffer, p.view.byteOffset + p.off, len);
        p.off += len;
        return new Uint8Array(buf); // Copy to avoid side effects
      }
      return _jsBinReadString(p);

    case 12: return _jsBinReadStruct(p, schemas[typeName], schemas);
    case 13: // Map
      var emWtK = p.view.getUint8(p.off++);
      var emWtV = p.view.getUint8(p.off++);
      var lenM = _jsBinReadI32(p);
      var objM = {};
      var mm = (typeName.match(/map<([^,]+),(.+)>/i) || []);
      var kt = mm[1] ? mm[1].trim() : "string";
      var vt = mm[2] ? mm[2].trim() : "string";
      var ket = _elemType(kt);
      var vet = _elemType(vt);
      for (var k = 0; k < lenM; k++) {
        var key = _jsBinReadValue(p, ket, kt, schemas);
        objM[String(key)] = _jsBinReadValue(p, vet, vt, schemas);
      }
      return objM;
    case 14: // Set
    case 15: // List
      var emWt = p.view.getUint8(p.off++);
      var len = _jsBinReadI32(p);
      var arr = [];
      var em = (typeName.match(/^(?:list|set)<(.+)>$/i) || [])[1] || "int32";
      var eet = _elemType(em);
      for (var j = 0; j < len; j++) arr.push(_jsBinReadValue(p, eet, em, schemas));
      return arr;
    default: 
      _jsBinSkip(p, wt);
      return null;
  }
}

function _jsBinReadStruct(p, schema, schemas) {
  var obj = {};
  if (!schema) return obj;
  if (!p.depth) p.depth = 0;
  if (++p.depth > 64) {
    throw new Error("Max recursion depth exceeded");
  }
  while (true) {
    var wt = p.view.getUint8(p.off++);
    if (wt === 0) break;
    var id = _jsBinReadI16(p);
    var f = schema.fields[id];
    if (f) {
      obj[f.name] = _jsBinReadValue(p, f.type, f.typeName, schemas);
    } else {
      _jsBinSkip(p, wt);
    }
  }
  p.depth--;
  return obj;
}

function _structToBinary(schema, obj, schemas) {
  var a = [];
  _jsBinWriteStruct(a, schema, obj, schemas);
  return new Uint8Array(a);
}
function _structFromBinary(schema, buf, schemas) {
  var u8 = buf && buf.buffer ? new Uint8Array(buf.buffer, buf.byteOffset, buf.byteLength) : new Uint8Array(buf || []);
  var p = { view: new DataView(u8.buffer, u8.byteOffset, u8.byteLength), off: 0 };
  return _jsBinReadStruct(p, schema, schemas);
}

function _toDpWireType(t) {
  var x = String(t).toLowerCase();
  if (x === "bool") return 2;
  if (x === "byte" || x === "int8") return 3;
  if (x === "double" || x === "float") return 4;
  if (x === "int16") return 6;
  if (x === "int32" || x === "enum") return 8;
  if (x === "int64") return 10;
  if (x === "string" || x === "binary") return 11;
  if (x === "struct") return 12;
  if (x === "map") return 13;
  if (x === "set") return 14;
  if (x === "list") return 15;
  return 0; // Stop
}

const _schema_TestEnum = {"name":"TestEnum","type":"enum","values":{"Alpha":1,"Beta":2,"Gamma":3}};
const TestEnum = {
  values: _schema_TestEnum.values,
  getSchema() { return _schema_TestEnum; }
};


const _schema_RoundtripModel = {"name":"RoundtripModel","type":"struct","fields":{"1":{"id":1,"name":"b_val","type":"bool","typeName":"bool","required":false,"defaultValue":"true"},"2":{"id":2,"name":"i8_val","type":"int8","typeName":"int8","required":false,"defaultValue":8},"3":{"id":3,"name":"i16_val","type":"int16","typeName":"int16","required":false,"defaultValue":1616},"4":{"id":4,"name":"i32_val","type":"int32","typeName":"int32","required":false,"defaultValue":323232},"5":{"id":5,"name":"i64_val","type":"int64","typeName":"int64","required":false,"defaultValue":6464646464},"6":{"id":6,"name":"f_val","type":"float","typeName":"float","required":false,"defaultValue":3.14},"7":{"id":7,"name":"d_val","type":"double","typeName":"double","required":false,"defaultValue":2.71828},"8":{"id":8,"name":"s_val","type":"string","typeName":"string","required":false,"defaultValue":"Hello DeukPack World"},"9":{"id":9,"name":"bin_val","type":"binary","typeName":"binary","required":false,"defaultValue":null},"10":{"id":10,"name":"i32_list","type":"list","typeName":"list<int32>","required":false,"defaultValue":null},"11":{"id":11,"name":"s_list","type":"list","typeName":"list<string>","required":false,"defaultValue":null},"12":{"id":12,"name":"s_i32_map","type":"map","typeName":"map<string,int32>","required":false,"defaultValue":null},"13":{"id":13,"name":"nested","type":"struct","typeName":"NestedStruct","required":false,"defaultValue":null}}};
const RoundtripModel = {
  getSchema() { return _schema_RoundtripModel; },
  create() { return {}; },
  toJson(obj, fieldIds, overrides) { return JSON.stringify(_toDpJsonFiltered(_schema_RoundtripModel, obj, _schemas, fieldIds, overrides)); },
  fromJson(str) { return _fromDpJson(_schema_RoundtripModel, JSON.parse(str || "{}"), _schemas); },
  toBinary(obj, fieldIds, overrides) { return _structToPackBinaryFiltered(_schema_RoundtripModel, obj, _schemas, fieldIds, overrides); },
  fromBinary(buf) { return _structFromPackBinary(_schema_RoundtripModel, buf, _schemas); },
  fromExcel(sheet, row) { return _fromExcelRow(_schema_RoundtripModel, sheet, row, _schemas, _enums); },
  fromExcelSheet(sheet, firstRow) { return _fromExcelSheet(_schema_RoundtripModel, sheet, _schemas, _enums, firstRow); },
  FieldId: { B_val: 1, I8_val: 2, I16_val: 3, I32_val: 4, I64_val: 5, F_val: 6, D_val: 7, S_val: 8, Bin_val: 9, I32_list: 10, S_list: 11, S_i32_map: 12, Nested: 13 }
};


const _schema_NestedStruct = {"name":"NestedStruct","type":"struct","fields":{"1":{"id":1,"name":"inner_val","type":"string","typeName":"string","required":false,"defaultValue":"inner"},"2":{"id":2,"name":"numbers","type":"list","typeName":"list<int32>","required":false,"defaultValue":null}}};
const NestedStruct = {
  getSchema() { return _schema_NestedStruct; },
  create() { return {}; },
  toJson(obj, fieldIds, overrides) { return JSON.stringify(_toDpJsonFiltered(_schema_NestedStruct, obj, _schemas, fieldIds, overrides)); },
  fromJson(str) { return _fromDpJson(_schema_NestedStruct, JSON.parse(str || "{}"), _schemas); },
  toBinary(obj, fieldIds, overrides) { return _structToPackBinaryFiltered(_schema_NestedStruct, obj, _schemas, fieldIds, overrides); },
  fromBinary(buf) { return _structFromPackBinary(_schema_NestedStruct, buf, _schemas); },
  fromExcel(sheet, row) { return _fromExcelRow(_schema_NestedStruct, sheet, row, _schemas, _enums); },
  fromExcelSheet(sheet, firstRow) { return _fromExcelSheet(_schema_NestedStruct, sheet, _schemas, _enums, firstRow); },
  FieldId: { Inner_val: 1, Numbers: 2 }
};


const _schema_EnumModel = {"name":"EnumModel","type":"struct","fields":{"1":{"id":1,"name":"e_val","type":"enum","typeName":"TestEnum","required":false,"defaultValue":"Beta"}}};
const EnumModel = {
  getSchema() { return _schema_EnumModel; },
  create() { return {}; },
  toJson(obj, fieldIds, overrides) { return JSON.stringify(_toDpJsonFiltered(_schema_EnumModel, obj, _schemas, fieldIds, overrides)); },
  fromJson(str) { return _fromDpJson(_schema_EnumModel, JSON.parse(str || "{}"), _schemas); },
  toBinary(obj, fieldIds, overrides) { return _structToPackBinaryFiltered(_schema_EnumModel, obj, _schemas, fieldIds, overrides); },
  fromBinary(buf) { return _structFromPackBinary(_schema_EnumModel, buf, _schemas); },
  fromExcel(sheet, row) { return _fromExcelRow(_schema_EnumModel, sheet, row, _schemas, _enums); },
  fromExcelSheet(sheet, firstRow) { return _fromExcelSheet(_schema_EnumModel, sheet, _schemas, _enums, firstRow); },
  FieldId: { E_val: 1 }
};


var _schemas = {};
_schemas["RoundtripModel"] = _schema_RoundtripModel;
_schemas["deuk.test.RoundtripModel"] = _schema_RoundtripModel;
_schemas["NestedStruct"] = _schema_NestedStruct;
_schemas["deuk.test.NestedStruct"] = _schema_NestedStruct;
_schemas["EnumModel"] = _schema_EnumModel;
_schemas["deuk.test.EnumModel"] = _schema_EnumModel;
var _enums = {};
_enums["TestEnum"] = _schema_TestEnum;
_enums["deuk.test.TestEnum"] = _schema_TestEnum;

if (typeof module !== "undefined" && module.exports) {
  module.exports.TestEnum = TestEnum;
  module.exports.RoundtripModel = RoundtripModel;
  module.exports.NestedStruct = NestedStruct;
  module.exports.EnumModel = EnumModel;
  module.exports._schemas = _schemas;
  module.exports._enums = _enums;
  module.exports._packStructToBinary = _packStructToBinary;
  module.exports._packBinaryToStruct = _packBinaryToStruct;
  module.exports._structToBinary = _structToBinary;
  module.exports._structFromBinary = _structFromBinary;
  module.exports._toDpJson = _toDpJson;
  module.exports._fromDpJson = _fromDpJson;
  module.exports._wrapDpJson = _wrapDpJson;
  module.exports._unwrapDpJson = _unwrapDpJson;
}
